#!/usr/bin/env python3
"""Translate plugin/index.mdx and plugin/tools/index.mdx"""
import os
import pathlib

def translate(filepath, pairs):
    content = open(filepath, encoding='utf-8').read()
    changed = False
    for old, new in pairs:
        if old in content:
            content = content.replace(old, new, 1)
            changed = True
        else:
            pass  # Already translated or not present
    if changed:
        with open(filepath, 'w', encoding='utf-8', newline='') as f:
            f.write(content)
        print(f'TRANSLATED: {os.path.basename(filepath)}')
    else:
        print(f'UNCHANGED: {os.path.basename(filepath)}')

BASE = pathlib.Path(__file__).resolve().parents[1] / "docs"

# ============================================================
# plugin/index.mdx
# ============================================================
translate(f'{BASE}/features/extensibility/plugin/index.mdx', [
    ('title: "Tools & Functions (Plugins)"', 'title: "Tools & Functions（插件）"'),
    ('# \U0001f6e0\ufe0f Tools & Functions\n\n:::danger \u26a0\ufe0f Critical Security Warning\n\n**Tools, Functions, Pipes, Filters, and Pipelines execute arbitrary Python code on your server.** This is by design\u2014it\'s what makes them powerful. However, this also means:\n\n1. **Only install from trusted sources.** Never import Tools or Functions from unknown or untrusted sources. Malicious code can compromise your entire system.\n\n2. **Review code before importing.** Before installing any community Tool or Function, review its source code. If you don\'t understand what it does, don\'t install it.\n\n3. **Protect your data directory.** The `data` directory (mounted at `/app/backend/data` in Docker) contains your database, configurations, and cached Tools/Functions. If an attacker gains write access to this directory, they can inject malicious code that will execute on your server.\n\n4. **Restrict Workspace access.** Only trusted administrators should have permission to create, import, or modify Tools and Functions. Regular users should **not** have Workspace access unless explicitly required.\n\n5. **Audit installed plugins regularly.** Periodically review the Tools and Functions installed in your instance via **Workspace \u2192 Tools** and **Admin Panel \u2192 Functions**.\n\n**What could go wrong?** A malicious Tool or Function could exfiltrate data, install malware, mine cryptocurrency, pivot to other systems on your network, or corrupt your instance.\n\n:::',
     '# 🛠️ Tools & Functions\n\n:::danger ⚠️ 重要安全警告\n\n**Tools、Functions、Pipes、Filters 和 Pipelines 在你的服务器上执行任意 Python 代码。** 这是设计上的特性——也是它们强大的原因。但这也意味着：\n\n1. **只从受信任的来源安装。** 切勿从未知或不受信任的来源导入 Tools 或 Functions。恶意代码可能危害你的整个系统。\n\n2. **导入前审查代码。** 安装任何社区 Tool 或 Function 之前，先审查其源代码。如果你不明白它的功能，就不要安装。\n\n3. **保护你的数据目录。** `data` 目录（在 Docker 中挂载为 `/app/backend/data`）包含你的数据库、配置以及缓存的 Tools/Functions。如果攻击者获得该目录的写入权限，他们可以注入将在你服务器上执行的恶意代码。\n\n4. **限制 Workspace 访问。** 只有受信任的管理员才应有权限创建、导入或修改 Tools 和 Functions。普通用户**不应该**拥有 Workspace 访问权限，除非明确需要。\n\n5. **定期审查已安装的插件。** 定期通过 **Workspace → Tools** 和**管理面板 → Functions** 检查实例中安装的 Tools 和 Functions。\n\n**可能出什么问题？** 恶意 Tool 或 Function 可能泄露数据、安装恶意软件、挖取加密货币、横向移动到你网络中的其他系统，或损坏你的实例。\n\n:::'),
    ('## TL;DR\n\n- **Tools** extend the abilities of LLMs, allowing them to collect real-world, real-time data like weather, stock prices, etc.\n- **Functions** extend the capabilities of the Open WebUI itself, enabling you to add new AI model support (like Anthropic or Vertex AI) or improve usability (like creating custom buttons or filters).\n- **Pipelines** are more for advanced users who want to transform Open WebUI features into API-compatible workflows\u2014mainly for offloading heavy processing.',
     '## 简介\n\n- **Tools** 扩展 LLM 的能力，使其能够收集天气、股票价格等实时的现实世界数据。\n- **Functions** 扩展 Open WebUI 本身的能力，使你能够添加新的 AI 模型支持（如 Anthropic 或 Vertex AI）或改善可用性（如创建自定义按钮或过滤器）。\n- **Pipelines** 更适合高级用户，他们希望将 Open WebUI 功能转换为 API 兼容的工作流——主要用于卸载重量级处理。'),
    ('Getting started with Tools and Functions is easy because everything\'s already built into the core system! You just **click a button** and **import these features directly from the community**, so there\'s no coding or deep technical work required.',
     '开始使用 Tools 和 Functions 很简单，因为一切都已内置在核心系统中！你只需**点击一个按钮**并**直接从社区导入这些功能**，无需编码或深入的技术工作。'),
    (':::tip Plugins can do *way* more than you think \u2014 and way more than is shown here\nThe pages that follow document every capability the plugin system exposes: every class shape, every lifecycle method, every `__arg__`, every event type, every return contract, every hook that touches the pipeline. That surface is *complete*.\n\nWhat\'s **not** documented \u2014 because it can\'t be \u2014 is **what to use it for**. The ideas. The creative combinations. The "huh, I didn\'t realize you could do that with just an inlet filter and a `saveState` bridge" moments. Those live in the community\'s heads, not in these docs.\n\nThese are **developer docs**. The primitives are all here; the creativity is on you (and on the thousands of community plugins that have already stretched the system into shapes nobody on the core team predicted \u2014 live-streaming HTML dashboards, per-user cost enforcement, summarize-and-replace context managers, bidirectional interactive UIs, entire embedded design systems, in-chat MCP apps, forensic watermarking, and so on).\n\nIf you\'re weighing a feature request and thinking *"this needs a core change,"* ask *"can this be a plugin?"* first. Almost always the answer is yes.\n:::',
     ':::tip 插件能做的远超你的想象——也远超这里展示的内容\n后续页面记录了插件系统暴露的每项能力：每个类的结构、每个生命周期方法、每个 `__arg__`、每种事件类型、每个返回契约、每个接触 pipeline 的钩子。这个界面是*完整的*。\n\n**未**记录的——因为无法记录的——是**用它来做什么**。那些创意。那些创造性的组合。那些"哦，我没意识到只用一个 inlet filter 和 `saveState` 桥接就能做到这一点"的瞬间。那些存在于社区成员的脑海中，不在这些文档里。\n\n这些是**开发者文档**。所有原语都在这里；创意在于你（还有已经将系统延伸到核心团队没人预测到的形态的数千个社区插件——实时流式 HTML 仪表板、按用户执行成本控制、摘要替换上下文管理器、双向交互式 UI、完整的嵌入式设计系统、对话内 MCP 应用、取证水印等等）。\n\n如果你在权衡功能请求，心想*"这需要核心改动，"*先问问*"这能成为插件吗？"* 几乎总是肯定的答案。\n:::'),
    ('## What are "Tools" and "Functions"?\n\nLet\'s start by thinking of **Open WebUI** as a "base" software that can do many tasks related to using Large Language Models (LLMs). But sometimes, you need extra features or abilities that don\'t come *out of the box*\u2014this is where **tools** and **functions** come into play.',
     '## 什么是"Tools"和"Functions"？\n\n让我们先把 **Open WebUI** 看作一个可以完成许多与大型语言模型（LLM）相关任务的"基础"软件。但有时你需要额外的功能或能力，这些功能不是*开箱即用*的——这就是 **Tools** 和 **Functions** 发挥作用的地方。'),
    ('### Tools\n\n**Tools** are an exciting feature because they allow LLMs to do more than just process text. They provide **external abilities** that LLMs wouldn\'t otherwise have on their own.',
     '### Tools\n\n**Tools** 是一个令人兴奋的功能，因为它们允许 LLM 做的不仅仅是处理文本。它们提供了 LLM 自身没有的**外部能力**。'),
    ('#### Example of a Tool:\n\nImagine you\'re chatting with an LLM and you want it to give you the latest weather update or stock prices in real time. Normally, the LLM can\'t do that because it\'s just working on pre-trained knowledge. This is where **tools** come in!\n\n- **Tools are like plugins** that the LLM can use to gather **real-world, real-time data**. So, with a "weather tool" enabled, the model can go out on the internet, gather live weather data, and display it in your conversation.\n\nTools are essentially **abilities** you\'re giving your AI to help it interact with the outside world. By adding these, the LLM can "grab" useful information or perform specialized tasks based on the context of the conversation.',
     '#### Tool 示例：\n\n想象你正在与 LLM 聊天，想让它实时给你提供最新天气或股票价格。通常，LLM 无法做到这一点，因为它只基于预训练知识工作。这就是 **Tools** 的用武之地！\n\n- **Tools 就像插件**，LLM 可以使用它们收集**现实世界的实时数据**。因此，启用"天气工具"后，模型可以上网、收集实时天气数据，并在你的对话中显示。\n\nTools 本质上是你给 AI 的**能力**，帮助它与外部世界互动。添加这些能力后，LLM 可以根据对话上下文"获取"有用信息或执行专门任务。'),
    ('#### Examples of Tools (extending LLM\'s abilities):\n\n1. **Real-time weather predictions** \U0001f6f0\ufe0f.\n2. **Stock price retrievers** \U0001f4c8.\n3. **Flight tracking information** \u2708\ufe0f.',
     '#### Tools 示例（扩展 LLM 的能力）：\n\n1. **实时天气预报** 🛰️。\n2. **股价查询** 📈。\n3. **航班追踪信息** ✈️。'),
    ('### Functions\n\nWhile **tools** are used by the AI during a conversation, **functions** help extend or customize the capabilities of Open WebUI itself. Imagine tools are like adding new ingredients to a dish, and functions are the process you use to control the kitchen! \U0001f6aa',
     '### Functions\n\n**Tools** 由 AI 在对话过程中使用，而 **Functions** 则帮助扩展或定制 Open WebUI 本身的能力。想象一下，Tools 就像给菜肴添加新食材，Functions 则是你用来控制厨房的流程！🚪'),
    ('#### Let\'s break that down:\n\n- **Functions** give you the ability to tweak or add **features** inside **Open WebUI** itself.\n- You\'re not giving new abilities to the LLM, but instead, you\'re extending the **interface, behavior, or logic** of the platform itself!\n\nFor instance, maybe you want to:\n\n1. Add a new AI model like **Anthropic** to the WebUI.\n2. Create a custom button in your toolbar that performs a frequently used command.\n3. Implement a better **filter** function that catches inappropriate or **spammy messages** from the incoming text.\n\nWithout functions, these would all be out of reach. But with this framework in Open WebUI, you can easily extend these features!',
     '#### 让我们分解一下：\n\n- **Functions** 让你能够调整或添加 **Open WebUI** 本身的**功能**。\n- 你不是在给 LLM 新的能力，而是在扩展平台本身的**界面、行为或逻辑**！\n\n例如，你可能想要：\n\n1. 向 WebUI 添加新的 AI 模型，如 **Anthropic**。\n2. 在工具栏中创建一个执行常用命令的自定义按钮。\n3. 实现一个更好的**过滤器**函数，过滤传入文本中不当或**垃圾消息**。\n\n没有 Functions，这些都无法实现。但通过 Open WebUI 中的这个框架，你可以轻松扩展这些功能！'),
    ('### Where to Find and Manage Functions\n\nFunctions are not located in the same place as Tools.\n\n- **Tools** are about model access and live in your **Workspace tabs** (where you add models, prompts, and knowledge collections). They can be added by users if granted permissions.\n- **Functions** are about **platform customization** and are found in the **Admin Panel**.\n  They are configured and managed only by admins who want to extend the platform interface or behavior for all users.',
     '### 在哪里找到和管理 Functions\n\nFunctions 与 Tools 不在同一位置。\n\n- **Tools** 关于模型访问，位于你的 **Workspace 标签页**（在那里你添加模型、提示词和知识集合）。如果获得授权，用户可以添加它们。\n- **Functions** 关于**平台定制**，位于**管理面板**。\n  它们只能由想要为所有用户扩展平台界面或行为的管理员配置和管理。'),
    ('### Summary of Differences:\n\n- **Tools** are things that allow LLMs to **do more things** outside their default abilities (such as retrieving live info or performing custom tasks based on external data).\n- **Functions** help the WebUI itself **do more things**, like adding new AI models or creating smarter ways to filter data.\n\nBoth are designed to be **pluggable**, meaning you can easily import them into your system with just one click from the community! \U0001f389 You won\'t have to spend hours coding or tinkering with them.',
     '### 差异总结：\n\n- **Tools** 让 LLM 能够**做更多事情**，超出其默认能力（如检索实时信息或基于外部数据执行自定义任务）。\n- **Functions** 帮助 WebUI 本身**做更多事情**，如添加新的 AI 模型或创建更智能的数据过滤方式。\n\n两者都设计为**可插拔的**，这意味着你可以通过社区的一键点击轻松将它们导入系统！🎉 你不必花费数小时编码或摆弄它们。'),
    ('## What are Pipelines?\n\nAnd then, we have **Pipelines**\u2026 Here\'s where things start to sound pretty technical\u2014but don\'t despair.\n\n**Pipelines** are part of an Open WebUI initiative focused on making every piece of the WebUI **inter-operable with OpenAI\'s API system**. Essentially, they extend what both **Tools** and **Functions** can already do, but now with even more flexibility. They allow you to turn features into OpenAI API-compatible formats. \U0001f9e0',
     '## 什么是 Pipelines？\n\n然后，我们有 **Pipelines**……这里开始听起来相当技术性——但不要绝望。\n\n**Pipelines** 是 Open WebUI 计划的一部分，专注于使 WebUI 的每个部分**与 OpenAI 的 API 系统互操作**。本质上，它们扩展了 **Tools** 和 **Functions** 已经能做的事情，但现在具有更大的灵活性。它们允许你将功能转换为 OpenAI API 兼容格式。🧠'),
    ('### But here\'s the thing\u2026\n\nYou likely **won\'t need** pipelines unless you\'re dealing with super-advanced setups.\n\n- **Who are pipelines for?** Typically, **experts** or people running more complicated use cases.\n- **When do you need them?** If you\'re trying to offload processing from your primary Open WebUI instance to a different machine (so you don\'t overload your primary system).\n\nIn most cases, as a beginner or even an intermediate user, you won\'t have to worry about pipelines. Just focus on enjoying the benefits that **tools** and **functions** bring to your Open WebUI experience!',
     '### 但关键是……\n\n除非你处理超高级设置，否则你可能**不需要** Pipelines。\n\n- **Pipelines 适合谁？** 通常是**专家**或运行更复杂用例的人。\n- **什么时候需要？** 如果你想从主 Open WebUI 实例将处理卸载到另一台机器（这样就不会使主系统过载）。\n\n在大多数情况下，作为初学者甚至中级用户，你不必担心 Pipelines。只需专注于享受 **Tools** 和 **Functions** 为你的 Open WebUI 体验带来的好处！'),
    ('## Want to Try? \U0001f680\n\nJump into Open WebUI, head over to the community section, and try importing a tool like **weather updates** or maybe adding a new feature to the toolbar with a function. Exploring these tools will show you how powerful and flexible Open WebUI can be!\n\n\U0001f31f There\'s always more to learn, so stay curious and keep experimenting!',
     '## 想要尝试？🚀\n\n进入 Open WebUI，前往社区部分，尝试导入像**天气更新**这样的工具，或者也许通过 Function 向工具栏添加新功能。探索这些工具将向你展示 Open WebUI 可以有多强大、多灵活！\n\n🌟 总有更多东西可以学习，所以保持好奇心，继续探索！'),
])

print('Done!')
