import os
import pathlib

DOCS = pathlib.Path(__file__).resolve().parents[1] / "docs"
filepath = DOCS / "reference/database-schema.md"
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ('## Automation Table', '## Automation 表'),
    ('| name            | Text          | NOT NULL                | Automation display name |',
     '| name            | Text          | NOT NULL                | 自动化的显示名称 |'),
    ('| data            | JSON          | NOT NULL                | Automation payload (`prompt`, `model_id`, `rrule`, optional terminal config) |',
     '| data            | JSON          | NOT NULL                | 自动化有效负载 (`prompt`, `model_id`, `rrule`, 可选终端配置) |'),
    ('| meta            | JSON          | nullable                | Optional metadata |',
     '| meta            | JSON          | nullable                | 可选元数据 |'),
    ('| is_active       | Boolean       | NOT NULL, default=True  | Active/paused state |',
     '| is_active       | Boolean       | NOT NULL, default=True  | 激活/暂停状态 |'),
    ('| last_run_at     | BigInteger    | nullable                | Last execution time |',
     '| last_run_at     | BigInteger    | nullable                | 上次执行时间 |'),
    ('| next_run_at     | BigInteger    | nullable                | Next scheduled execution time |',
     '| next_run_at     | BigInteger    | nullable                | 下一次计划执行时间 |'),
    ('Things to know about the automation table:', '关于 automation 表的注意事项：'),
    ('- `next_run_at` is indexed for efficient due-run polling.', '- `next_run_at` 已建立索引以便进行高效的到期运行轮询。'),
    ('- `data.rrule` defines recurrence and drives scheduler calculations.', '- `data.rrule` 定义了重复发生频率并驱动调度器计算。'),
    ('## Automation Run Table', '## Automation Run 表'),
    ('| automation_id   | Text          | NOT NULL        | Reference to automation |',
     '| automation_id   | Text          | NOT NULL        | 对自动化的引用 |'),
    ('| chat_id         | Text          | nullable        | Chat created by this run (if available) |',
     '| chat_id         | Text          | nullable        | 此次运行创建的聊天（如果可用） |'),
    ('| status          | Text          | NOT NULL        | Run status (`success` / `error`) |',
     '| status          | Text          | NOT NULL        | 运行状态 (`success` / `error`) |'),
    ('| error           | Text          | nullable        | Error details when status is `error` |',
     '| error           | Text          | nullable        | 当状态为 `error` 时的错误详情 |'),
    ('| created_at      | BigInteger    | NOT NULL        | Execution record timestamp |',
     '| created_at      | BigInteger    | NOT NULL        | 执行记录时间戳 |'),
    ('Things to know about the automation_run table:', '关于 automation_run 表的注意事项：'),
    ('- Indexed by `automation_id` for fast per-automation run history queries.', '- 在 `automation_id` 上建立索引以快速查询每个自动化的运行历史。'),
    ('- Rows are deleted when an automation is deleted.', '- 删除自动化时删除关联行。'),
    ('## Calendar Table', '## Calendar 表'),
    ('| name            | Text          | NOT NULL                | Calendar display name              |',
     '| name            | Text          | NOT NULL                | 日历显示名称              |'),
    ('| color           | Text          | nullable                | Display color (hex, e.g. `#3b82f6`) |',
     '| color           | Text          | nullable                | 显示颜色（十六进制，例如 `#3b82f6`） |'),
    ('| is_default      | Boolean       | NOT NULL, default=False | Whether this is the user\'s default calendar |',
     '| is_default      | Boolean       | NOT NULL, default=False | 这是否是用户的默认日历 |'),
    ('| data            | JSON          | nullable                | Extensible data payload            |',
     '| data            | JSON          | nullable                | 可扩展的数据有效负载            |'),
    ('Things to know about the calendar table:', '关于 calendar 表的注意事项：'),
    ('- Indexed on `user_id` for efficient per-user calendar listing.', '- 在 `user_id` 上建立索引以高效列出每个用户的日历。'),
    ('- A default "Personal" calendar is auto-created on first access.', '- 在首次访问时自动创建一个默认的“Personal”（个人）日历。'),
    ('- The "Scheduled Tasks" calendar is **virtual** — it is not stored in this table. Instead, the API synthesizes it at response time (with constant ID `__scheduled_tasks__`) for users who have Automations access. Automation RRULE future runs and past execution records are rendered as virtual events on this calendar.', '- “Scheduled Tasks”（计划任务）日历是**虚拟的** — 它不存储在此表中。相反，对于具有自动化访问权限的用户，API 在响应时（使用恒定 ID `__scheduled_tasks__`）综合出它。自动化 RRULE 的未来运行和过去的执行记录都会作为该日历上的虚拟事件呈现。'),
    ('- Access control is managed via the `access_grant` table with `resource_type = \'calendar\'`, enabling calendar sharing between users and groups.', '- 访问控制通过 `access_grant` 表（`resource_type = \'calendar\'`）进行管理，从而实现用户和组之间的日历共享。'),
    ('- A user can only delete non-default calendars. Deleting a calendar cascades to all its events, attendees, and access grants.', '- 用户只能删除非默认日历。删除日历会级联到其所有事件、参与者和访问授权。'),
    ('## Calendar Event Table', '## Calendar Event 表'),
    ('| calendar_id     | Text          | NOT NULL                | Reference to parent calendar       |',
     '| calendar_id     | Text          | NOT NULL                | 对父日历的引用       |'),
    ('| user_id         | Text          | NOT NULL                | User who created the event         |',
     '| user_id         | Text          | NOT NULL                | 创建事件的用户         |'),
    ('| title           | Text          | NOT NULL                | Event title                        |',
     '| title           | Text          | NOT NULL                | 事件标题                        |'),
    ('| description     | Text          | nullable                | Event description                  |',
     '| description     | Text          | nullable                | 事件描述                  |'),
    ('| start_at        | BigInteger    | NOT NULL                | Start time (epoch nanoseconds)     |',
     '| start_at        | BigInteger    | NOT NULL                | 开始时间（纪元纳秒）     |'),
    ('| end_at          | BigInteger    | nullable                | End time (epoch nanoseconds)       |',
     '| end_at          | BigInteger    | nullable                | 结束时间（纪元纳秒）       |'),
    ('| all_day         | Boolean       | NOT NULL, default=False | Whether this is an all-day event   |',
     '| all_day         | Boolean       | NOT NULL, default=False | 这是否是一个全天事件   |'),
    ('| rrule           | Text          | nullable                | iCalendar RRULE for recurrence     |',
     '| rrule           | Text          | nullable                | 用于重复发生的 iCalendar RRULE     |'),
    ('| color           | Text          | nullable                | Per-event color override           |',
     '| color           | Text          | nullable                | 每个事件颜色覆盖           |'),
    ('| location        | Text          | nullable                | Event location                     |',
     '| location        | Text          | nullable                | 事件位置                     |'),
    ('| meta            | JSON          | nullable                | Optional metadata (e.g. `automation_id`) |',
     '| meta            | JSON          | nullable                | 可选元数据（例如 `automation_id`） |'),
    ('| is_cancelled    | Boolean       | NOT NULL, default=False | Soft-cancel flag                   |',
     '| is_cancelled    | Boolean       | NOT NULL, default=False | 软取消标志                   |'),
    ('Things to know about the calendar_event table:', '关于 calendar_event 表的注意事项：'),
    ('- Composite index on (`calendar_id`, `start_at`) for efficient range queries within a calendar.', '- 在 (`calendar_id`, `start_at`) 上建立复合索引，以便在一个日历内进行高效的范围查询。'),
    ('- Composite index on (`user_id`, `start_at`) for efficient per-user date range queries.', '- 在 (`user_id`, `start_at`) 上建立复合索引，以便每个用户进行高效的日期范围查询。'),
    ('- Recurring events store an `rrule` string and are expanded into individual instances at query time (server-side Python expansion using `dateutil`).', '- 重复事件存储 `rrule` 字符串，并在查询时扩展为单独的实例（使用 `dateutil` 进行服务器端 Python 扩展）。'),
    ('- Cancelled events (`is_cancelled = True`) are excluded from range queries but retained in the database.', '- 取消的事件（`is_cancelled = True`）被排除在范围查询之外，但保留在数据库中。'),
    ('## Calendar Event Attendee Table', '## Calendar Event Attendee 表'),
    ('| event_id        | Text          | NOT NULL                           | Reference to the calendar event    |',
     '| event_id        | Text          | NOT NULL                           | 对日历事件的引用    |'),
    ('| user_id         | Text          | NOT NULL                           | User invited to the event          |',
     '| user_id         | Text          | NOT NULL                           | 被邀请参加事件的用户          |'),
    ('| status          | Text          | NOT NULL, default=\'pending\'        | RSVP status: `pending`, `accepted`, `declined`, `tentative` |',
     '| status          | Text          | NOT NULL, default=\'pending\'        | RSVP 状态：`pending`（待定）、`accepted`（已接受）、`declined`（已拒绝）、`tentative`（暂定） |'),
    ('Things to know about the calendar_event_attendee table:', '关于 calendar_event_attendee 表的注意事项：'),
    ('- Unique constraint on (`event_id`, `user_id`) to prevent duplicate attendee entries.', '- 在 (`event_id`, `user_id`) 上的唯一约束以防止重复的参与者条目。'),
    ('- Indexed on (`user_id`, `status`) for efficient lookups of events a user is invited to.', '- 在 (`user_id`, `status`) 上建立索引以高效查找邀请用户的事件。'),
    ('- Attendees are replaced in bulk when an event is updated with a new attendee list.', '- 当使用新参与者列表更新事件时，将批量替换参与者。'),
    ('- Deleting an event cascades to delete all attendee records.', '- 删除事件会级联删除所有参与者记录。')
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print("done db3")
