import os
import re

filepath = 'd:/Github/open-webui-docs/docs/reference/database-schema.md'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ('## Access Grant Table', '## Access Grant 表'),
    ('| **Column Name** | **Data Type** | **Constraints**         | **Description**                                        |',
     '| **列名** | **数据类型** | **约束**         | **描述**                                        |'),
    ('| id              | Integer       | PRIMARY KEY, AUTOINCREMENT | Unique identifier                                   |',
     '| id              | Integer       | PRIMARY KEY, AUTOINCREMENT | 唯一标识符                                   |'),
    ('| resource_type   | Text          | NOT NULL                | Type of resource (e.g., `model`, `knowledge`, `tool`)  |',
     '| resource_type   | Text          | NOT NULL                | 资源类型（例如：`model`, `knowledge`, `tool`）  |'),
    ('| resource_id     | Text          | NOT NULL                | ID of the specific resource                            |',
     '| resource_id     | Text          | NOT NULL                | 特定资源的 ID                            |'),
    ('| principal_type  | Text          | NOT NULL                | Type of grantee: `user` or `group`                     |',
     '| principal_type  | Text          | NOT NULL                | 授权对象类型：`user` 或 `group`                     |'),
    ('| principal_id    | Text          | NOT NULL                | ID of the user or group (or `*` for public)            |',
     '| principal_id    | Text          | NOT NULL                | 用户或组的 ID（或使用 `*` 表示公开）            |'),
    ('| permission      | Text          | NOT NULL                | Permission level: `read` or `write`                    |',
     '| permission      | Text          | NOT NULL                | 权限级别：`read` 或 `write`                    |'),
    ('| created_at      | BigInteger    | nullable                | Grant creation timestamp                               |',
     '| created_at      | BigInteger    | nullable                | 授权创建时间戳                               |'),
    ('Things to know about the access_grant table:', '关于 access_grant 表的注意事项：'),
    ('- Unique constraint on (`resource_type`, `resource_id`, `principal_type`, `principal_id`, `permission`) to prevent duplicate grants',
     '- 在 (`resource_type`, `resource_id`, `principal_type`, `principal_id`, `permission`) 上的唯一约束以防止重复授权'),
    ('- Indexed on (`resource_type`, `resource_id`) and (`principal_type`, `principal_id`) for efficient lookups',
     '- 在 (`resource_type`, `resource_id`) 和 (`principal_type`, `principal_id`) 上建立索引以提高查询效率'),
    ('- Replaces the former `access_control` JSON column that was previously embedded in each resource table',
     '- 替换了以前嵌入在每个资源表中的 `access_control` JSON 列'),
    ('- `principal_type` of `user` with `principal_id` of `*` represents public (open) access',
     '- `principal_type` 为 `user` 且 `principal_id` 为 `*` 表示公共（开放）访问权限'),
    ('- Supports both group-level and individual user-level access grants',
     '- 支持组级别和个人用户级别的访问授权'),
    ('## Auth Table', '## Auth 表'),
    ('| **Column Name** | **Data Type** | **Constraints** | **Description**   |',
     '| **列名** | **数据类型** | **约束** | **描述**   |'),
    ('| id              | String        | PRIMARY KEY     | Unique identifier |',
     '| id              | String        | PRIMARY KEY     | 唯一标识符 |'),
    ('| email           | String        | -               | User\'s email      |',
     '| email           | String        | -               | 用户邮箱      |'),
    ('| password        | Text          | -               | Hashed password   |',
     '| password        | Text          | -               | 哈希密码   |'),
    ('| active          | Boolean       | -               | Account status    |',
     '| active          | Boolean       | -               | 账户状态    |'),
    ('Things to know about the auth table:', '关于 auth 表的注意事项：'),
    ('- Uses UUID for primary key', '- 使用 UUID 作为主键'),
    ('- One-to-One relationship with `users` table (shared id)', '- 与 `users` 表一对一关系（共享 id）'),
    ('## Channel Table', '## Channel 表'),
    ('| id              | Text          | PRIMARY KEY     | Unique identifier (UUID)            |',
     '| id              | Text          | PRIMARY KEY     | 唯一标识符 (UUID)            |'),
    ('| user_id         | Text          | -               | Owner/creator of channel            |',
     '| user_id         | Text          | -               | 频道的拥有者/创建者            |'),
    ('| type            | Text          | nullable        | Channel type                        |',
     '| type            | Text          | nullable        | 频道类型                        |'),
    ('| name            | Text          | -               | Channel name                        |',
     '| name            | Text          | -               | 频道名称                        |'),
    ('| description     | Text          | nullable        | Channel description                 |',
     '| description     | Text          | nullable        | 频道描述                 |'),
    ('| data            | JSON          | nullable        | Flexible data storage               |',
     '| data            | JSON          | nullable        | 灵活的数据存储               |'),
    ('| meta            | JSON          | nullable        | Channel metadata                    |',
     '| meta            | JSON          | nullable        | 频道元数据                    |'),
    ('| created_at      | BigInteger    | -               | Creation timestamp (nanoseconds)    |',
     '| created_at      | BigInteger    | -               | 创建时间戳（纳秒）    |'),
    ('| updated_at      | BigInteger    | -               | Last update timestamp (nanoseconds) |',
     '| updated_at      | BigInteger    | -               | 最后更新时间戳（纳秒） |'),
    ('- Case-insensitive channel names (stored lowercase)', '- 频道名称不区分大小写（以小写存储）'),
    ('## Channel Member Table', '## Channel Member 表'),
    ('| id              | TEXT          | NOT NULL        | Unique identifier for the channel membership |',
     '| id              | TEXT          | NOT NULL        | 频道成员资格的唯一标识符 |'),
    ('| channel_id      | TEXT          | NOT NULL        | Reference to the channel                     |',
     '| channel_id      | TEXT          | NOT NULL        | 对频道的引用                     |'),
    ('| user_id         | TEXT          | NOT NULL        | Reference to the user                        |',
     '| user_id         | TEXT          | NOT NULL        | 对用户的引用                        |'),
    ('| created_at      | BIGINT        | -               | Timestamp when membership was created        |',
     '| created_at      | BIGINT        | -               | 创建成员资格的时间戳        |'),
    ('## Channel File Table', '## Channel File 表'),
    ('| **Column Name** | **Data Type** | **Constraints**                    | **Description**                   |',
     '| **列名** | **数据类型** | **约束**                    | **描述**                   |'),
    ('| user_id         | Text          | NOT NULL                           | Owner of the relationship         |',
     '| user_id         | Text          | NOT NULL                           | 关系的拥有者         |'),
    ('| channel_id      | Text          | FOREIGN KEY(channel.id), NOT NULL  | Reference to the channel          |',
     '| channel_id      | Text          | FOREIGN KEY(channel.id), NOT NULL  | 对频道的引用          |'),
    ('| file_id         | Text          | FOREIGN KEY(file.id), NOT NULL     | Reference to the file             |',
     '| file_id         | Text          | FOREIGN KEY(file.id), NOT NULL     | 对文件的引用             |'),
    ('| message_id      | Text          | FOREIGN KEY(message.id), nullable  | Reference to associated message   |',
     '| message_id      | Text          | FOREIGN KEY(message.id), nullable  | 对关联消息的引用   |'),
    ('| created_at      | BigInteger    | NOT NULL                           | Creation timestamp                |',
     '| created_at      | BigInteger    | NOT NULL                           | 创建时间戳                |'),
    ('| updated_at      | BigInteger    | NOT NULL                           | Last update timestamp             |',
     '| updated_at      | BigInteger    | NOT NULL                           | 最后更新时间戳             |'),
    ('Things to know about the channel_file table:', '关于 channel_file 表的注意事项：'),
    ('- Unique constraint on (`channel_id`, `file_id`) to prevent duplicate entries', '- 在 (`channel_id`, `file_id`) 上的唯一约束以防止重复条目'),
    ('- Foreign key relationships with CASCADE delete', '- 带有 CASCADE 删除的外键关系'),
    ('- Indexed on `channel_id`, `file_id`, and `user_id` for performance', '- 在 `channel_id`, `file_id` 和 `user_id` 上建立索引以提高性能'),
    ('## Chat Table', '## Chat 表'),
    ('| user_id         | String        | -                       | Owner of the chat        |',
     '| user_id         | String        | -                       | 聊天的拥有者        |'),
    ('| title           | Text          | -                       | Chat title               |',
     '| title           | Text          | -                       | 聊天标题               |'),
    ('| chat            | JSON          | -                       | Chat content and history |',
     '| chat            | JSON          | -                       | 聊天内容和历史 |'),
    ('| share_id        | Text          | UNIQUE, nullable        | Sharing identifier       |',
     '| share_id        | Text          | UNIQUE, nullable        | 共享标识符       |'),
    ('| archived        | Boolean       | default=False           | Archive status           |',
     '| archived        | Boolean       | default=False           | 归档状态           |'),
    ('| pinned          | Boolean       | default=False, nullable | Pin status               |',
     '| pinned          | Boolean       | default=False, nullable | 置顶状态               |'),
    ('| meta            | JSON          | server_default="{}"     | Metadata including tags  |',
     '| meta            | JSON          | server_default="{}"     | 包含标签的元数据  |'),
    ('| folder_id       | Text          | nullable                | Parent folder ID         |',
     '| folder_id       | Text          | nullable                | 父文件夹 ID         |'),
    ('| tasks           | JSON          | nullable                | Chat-level task/todo list used by agentic workflows |',
     '| tasks           | JSON          | nullable                | 代理工作流使用的聊天级任务/待办事项列表 |'),
    ('| summary         | Text          | nullable                | Optional chat summary text |',
     '| summary         | Text          | nullable                | 可选的聊天摘要文本 |'),
    ('| last_read_at    | BigInteger    | nullable                | Last read timestamp used for unread indicators |',
     '| last_read_at    | BigInteger    | nullable                | 用于未读指示器的最后阅读时间戳 |'),
    ('Things to know about the chat table:', '关于 chat 表的注意事项：'),
    ('- `tasks` and `summary` support structured planning/status UX in chat sessions.', '- `tasks` 和 `summary` 支持聊天会话中的结构化计划/状态 UX。'),
    ('- `last_read_at` is used by sidebar unread state logic (compare with `updated_at`).', '- `last_read_at` 由侧边栏未读状态逻辑使用（与 `updated_at` 比较）。'),
    ('- `share_id` references the `shared_chat.id` token when the chat has an active share link.', '- 当聊天具有活动的分享链接时，`share_id` 引用 `shared_chat.id` 令牌。'),
    ('## Shared Chat Table', '## Shared Chat 表'),
    ('| **Column Name** | **Data Type** | **Constraints**                  | **Description**                    |',
     '| **列名** | **数据类型** | **约束**                  | **描述**                    |'),
    ('| id              | Text          | PRIMARY KEY                      | Share token (UUID) used in `/s/{id}` URLs |',
     '| id              | Text          | PRIMARY KEY                      | 用于 `/s/{id}` URL 的分享令牌 (UUID) |'),
    ('| chat_id         | Text          | FOREIGN KEY(chat.id) CASCADE, NOT NULL | Reference to the original chat |',
     '| chat_id         | Text          | FOREIGN KEY(chat.id) CASCADE, NOT NULL | 对原始聊天的引用 |'),
    ('| user_id         | Text          | NOT NULL                         | User who created the share         |',
     '| user_id         | Text          | NOT NULL                         | 创建分享的用户         |'),
    ('| title           | Text          | nullable                         | Chat title at time of sharing      |',
     '| title           | Text          | nullable                         | 分享时的聊天标题      |'),
    ('| chat            | JSON          | nullable                         | Snapshot of chat content at share time |',
     '| chat            | JSON          | nullable                         | 分享时的聊天内容快照 |'),
    ('| created_at      | BigInteger    | nullable                         | Share creation timestamp           |',
     '| created_at      | BigInteger    | nullable                         | 分享创建时间戳           |'),
    ('| updated_at      | BigInteger    | nullable                         | Last re-snapshot timestamp         |',
     '| updated_at      | BigInteger    | nullable                         | 最后重新快照时间戳         |'),
    ('Things to know about the shared_chat table:', '关于 shared_chat 表的注意事项：'),
    ('- Replaces the previous pattern of storing shared chat snapshots as phantom rows in the `chat` table with `user_id` set to `shared-{chat_id}`.', '- 替换了以前将共享聊天快照作为幽灵行存储在 `chat` 表中（`user_id` 设置为 `shared-{chat_id}`）的模式。'),
    ('- Each row is an immutable snapshot of the original chat at the time of sharing (or last re-share). The snapshot is updated when the user clicks "Update and Copy Link".', '- 每行都是原始聊天在共享（或最后一次重新共享）时不可变的快照。当用户点击“更新并复制链接”时会更新此快照。'),
    ('- Deleting the original chat cascades to delete the shared snapshot.', '- 删除原始聊天会级联删除共享快照。'),
    ('- Access control for shared chats is managed via the `access_grant` table with `resource_type = \'shared_chat\'`.', '- 共享聊天的访问控制通过 `access_grant` 表（`resource_type = \'shared_chat\'`）进行管理。')
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print("done db2")
