import os

filepath = 'd:/Github/open-webui-docs/docs/reference/database-schema.md'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ('## Chat ID Tag Table', '## Chat ID Tag 表'),
    ('| tag_name        | VARCHAR(255)  | NOT NULL        | Name of the tag    |',
     '| tag_name        | VARCHAR(255)  | NOT NULL        | 标签名称    |'),
    ('| chat_id         | VARCHAR(255)  | NOT NULL        | Reference to chat  |',
     '| chat_id         | VARCHAR(255)  | NOT NULL        | 聊天引用  |'),
    ('| user_id         | VARCHAR(255)  | NOT NULL        | Reference to user  |',
     '| user_id         | VARCHAR(255)  | NOT NULL        | 用户引用  |'),
    ('| timestamp       | INTEGER       | NOT NULL        | Creation timestamp |',
     '| timestamp       | INTEGER       | NOT NULL        | 创建时间戳 |'),
    ('## Config', '## Config 表'),
    ('| id              | INTEGER       | NOT NULL        | -                 | Primary key identifier |',
     '| id              | INTEGER       | NOT NULL        | -                 | 主键标识符 |'),
    ('| data            | JSON          | NOT NULL        | -                 | Configuration data     |',
     '| data            | JSON          | NOT NULL        | -                 | 配置数据     |'),
    ('| version         | INTEGER       | NOT NULL        | -                 | Config version number  |',
     '| version         | INTEGER       | NOT NULL        | -                 | 配置版本号  |'),
    ('| created_at      | DATETIME      | NOT NULL        | CURRENT_TIMESTAMP | Creation timestamp     |',
     '| created_at      | DATETIME      | NOT NULL        | CURRENT_TIMESTAMP | 创建时间戳     |'),
    ('| updated_at      | DATETIME      | -               | CURRENT_TIMESTAMP | Last update timestamp  |',
     '| updated_at      | DATETIME      | -               | CURRENT_TIMESTAMP | 最后更新时间戳  |'),
    ('## Feedback Table', '## Feedback 表'),
    ('| version         | BigInteger    | default=0       | Feedback version number         |',
     '| version         | BigInteger    | default=0       | 反馈版本号         |'),
    ('| type            | Text          | -               | Type of feedback                |',
     '| type            | Text          | -               | 反馈类型                |'),
    ('| data            | JSON          | nullable        | Feedback data including ratings |',
     '| data            | JSON          | nullable        | 包括评分在内的反馈数据 |'),
    ('| meta            | JSON          | nullable        | Metadata (arena, chat_id, etc)  |',
     '| meta            | JSON          | nullable        | 元数据 (arena, chat_id 等)  |'),
    ('| snapshot        | JSON          | nullable        | Associated chat snapshot        |',
     '| snapshot        | JSON          | nullable        | 关联的聊天快照        |'),
    ('## File Table', '## File 表'),
    ('| hash            | Text          | nullable        | File hash/checksum    |',
     '| hash            | Text          | nullable        | 文件哈希/校验和    |'),
    ('| filename        | Text          | -               | Name of the file      |',
     '| filename        | Text          | -               | 文件名称      |'),
    ('| path            | Text          | nullable        | File system path      |',
     '| path            | Text          | nullable        | 文件系统路径      |'),
    ('| data            | JSON          | nullable        | File-related data     |',
     '| data            | JSON          | nullable        | 文件相关数据     |'),
    ('| meta            | JSON          | nullable        | File metadata         |',
     '| meta            | JSON          | nullable        | 文件元数据         |'),
    ('The `meta` field\'s expected structure:', '`meta` 字段的预期结构：'),
    ('# Optional display name', '# 可选的显示名称'),
    ('# MIME type', '# MIME 类型'),
    ('# File size in bytes', '# 文件大小（以字节为单位）'),
    ('# Additional metadata supported via ConfigDict(extra="allow")', '# 通过 ConfigDict(extra="allow") 支持其他元数据'),
    ('## Folder Table', '## Folder 表'),
    ('| parent_id       | Text          | nullable        | Parent folder ID for hierarchy |',
     '| parent_id       | Text          | nullable        | 用于分层结构的父文件夹 ID |'),
    ('| items           | JSON          | nullable        | Folder contents                |',
     '| items           | JSON          | nullable        | 文件夹内容                |'),
    ('| is_expanded     | Boolean       | default=False   | UI expansion state             |',
     '| is_expanded     | Boolean       | default=False   | UI 展开状态             |'),
    ('Things to know about the folder table:', '关于 folder 表的注意事项：'),
    ('- Primary key is composite (`id`, `user_id`)', '- 主键是复合键 (`id`, `user_id`)'),
    ('- Folders can be nested (`parent_id` reference)', '- 文件夹可以嵌套（`parent_id` 引用）'),
    ('- Root folders have null `parent_id`', '- 根文件夹的 `parent_id` 为 null'),
    ('- Folder names must be unique within the same parent', '- 在同一父级文件夹内，文件夹名称必须唯一'),
    ('## Function Table', '## Function 表'),
    ('| type            | Text          | -               | Function type             |',
     '| type            | Text          | -               | 函数类型             |'),
    ('| content         | Text          | -               | Function content/code     |',
     '| content         | Text          | -               | 函数内容/代码     |'),
    ('| valves          | JSON          | -               | Function control settings |',
     '| valves          | JSON          | -               | 函数控制设置 |'),
    ('| is_active       | Boolean       | -               | Function active status    |',
     '| is_active       | Boolean       | -               | 函数激活状态    |'),
    ('| is_global       | Boolean       | -               | Global availability flag  |',
     '| is_global       | Boolean       | -               | 全局可用性标志  |'),
    ('Things to know about the function table:', '关于 function 表的注意事项：'),
    ('- `type` can only be: ["filter", "action"]', '- `type` 只能是：["filter", "action"]'),
    ('## Group Table', '## Group 表'),
    ('| permissions     | JSON          | nullable            | Permission configuration |',
     '| permissions     | JSON          | nullable            | 权限配置 |'),
    ('Note: The `user_ids` column has been migrated to the `group_member` table.', '注意：`user_ids` 列已迁移到 `group_member` 表。'),
    ('## Group Member Table', '## Group Member 表'),
    ('| group_id        | Text          | FOREIGN KEY(group.id), NOT NULL  | Reference to the group            |',
     '| group_id        | Text          | FOREIGN KEY(group.id), NOT NULL  | 引用该组            |'),
    ('Things to know about the group_member table:', '关于 group_member 表的注意事项：'),
    ('- Unique constraint on (`group_id`, `user_id`) to prevent duplicate memberships', '- 在 (`group_id`, `user_id`) 上的唯一约束以防止重复的成员资格'),
    ('- Foreign key relationships with CASCADE delete to group and user tables', '- 带有对 group 和 user 表的 CASCADE 删除的外键关系'),
    ('## Knowledge Table', '## Knowledge 表'),
    ('## Knowledge File Table', '## Knowledge File 表'),
    ('| knowledge_id    | Text          | FOREIGN KEY(knowledge.id), NOT NULL  | Reference to the knowledge base   |',
     '| knowledge_id    | Text          | FOREIGN KEY(knowledge.id), NOT NULL  | 引用知识库   |'),
    ('Things to know about the knowledge_file table:', '关于 knowledge_file 表的注意事项：'),
    ('- Unique constraint on (`knowledge_id`, `file_id`) to prevent duplicate entries', '- 在 (`knowledge_id`, `file_id`) 上的唯一约束以防止重复条目'),
    ('Access control for resources (models, knowledge bases, tools, prompts, notes, files, channels) is managed through the `access_grant` table rather than embedded JSON. Each grant entry specifies a resource, a principal (user or group), and a permission level (read or write). See the [Access Grant Table](#access-grant-table) section above for details.',
     '资源（模型、知识库、工具、提示词、笔记、文件、频道）的访问控制通过 `access_grant` 表进行管理，而不是嵌入式 JSON。每个授权条目指定一个资源、一个主体（用户或组）和一个权限级别（读取或写入）。详见上文的 [Access Grant 表](#access-grant-表)部分。'),
    ('## Memory Table', '## Memory 表'),
    ('## Message Table', '## Message 表'),
    ('| channel_id      | Text          | nullable        | Associated channel                  |',
     '| channel_id      | Text          | nullable        | 关联频道                  |'),
    ('| parent_id       | Text          | nullable        | Parent message for threads          |',
     '| parent_id       | Text          | nullable        | 会话串的父消息          |'),
    ('| content         | Text          | -               | Message content                     |',
     '| content         | Text          | -               | 消息内容                     |'),
    ('## Message Reaction Table', '## Message Reaction 表'),
    ('| message_id      | Text          | -               | Associated message       |',
     '| message_id      | Text          | -               | 关联消息       |'),
    ('| name            | Text          | -               | Reaction name/emoji      |',
     '| name            | Text          | -               | 反应名称/表情符号      |'),
    ('## Model Table', '## Model 表'),
    ('| base_model_id   | Text          | nullable        | Parent model reference |',
     '| base_model_id   | Text          | nullable        | 父模型引用 |'),
    ('| params          | JSON          | -               | Model parameters       |',
     '| params          | JSON          | -               | 模型参数       |'),
    ('## Note Table', '## Note 表'),
    ('| title           | Text          | nullable        | Note title                 |',
     '| title           | Text          | nullable        | 笔记标题                 |'),
    ('| is_pinned       | Boolean       | default=False, nullable | Whether the note is pinned to the sidebar |',
     '| is_pinned       | Boolean       | default=False, nullable | 笔记是否置顶到侧边栏 |'),
    ('## OAuth Session Table', '## OAuth Session 表'),
    ('| provider        | Text          | -                    | OAuth provider (e.g., \'google\')   |',
     '| provider        | Text          | -                    | OAuth 提供商（例如：\'google\'）   |'),
    ('| token           | Text          | -                    | OAuth session token               |',
     '| token           | Text          | -                    | OAuth 会话令牌               |'),
    ('| expires_at      | BigInteger    | -                    | Token expiration timestamp        |',
     '| expires_at      | BigInteger    | -                    | 令牌到期时间戳        |'),
    ('## Prompt Table', '## Prompt 表'),
    ('| command         | String        | UNIQUE, INDEX   | Unique command identifier           |',
     '| command         | String        | UNIQUE, INDEX   | 唯一命令标识符           |'),
    ('| name            | Text          | NOT NULL        | Display name of the prompt          |',
     '| name            | Text          | NOT NULL        | 提示词的显示名称          |'),
    ('| content         | Text          | NOT NULL        | Prompt content/template             |',
     '| content         | Text          | NOT NULL        | 提示词内容/模板             |'),
    ('| version_id      | Text          | nullable        | Current version identifier          |',
     '| version_id      | Text          | nullable        | 当前版本标识符          |'),
    ('| tags            | JSON          | nullable        | Associated tags                     |',
     '| tags            | JSON          | nullable        | 关联标签                     |'),
    ('## Prompt History Table', '## Prompt History 表'),
    ('| prompt_id       | Text          | FOREIGN KEY(prompt.id), INDEX  | Reference to the prompt           |',
     '| prompt_id       | Text          | FOREIGN KEY(prompt.id), INDEX  | 引用该提示词           |'),
    ('| parent_id       | Text          | nullable                       | Reference to the parent version   |',
     '| parent_id       | Text          | nullable                       | 引用父版本   |'),
    ('| snapshot        | JSON          | NOT NULL                       | Snapshot of the prompt at version |',
     '| snapshot        | JSON          | NOT NULL                       | 提示词版本快照 |'),
    ('| commit_message  | Text          | nullable                       | Version commit message            |',
     '| commit_message  | Text          | nullable                       | 版本提交信息            |'),
    ('## Skill Table', '## Skill 表'),
    ('| description     | Text          | nullable        | Short description (used in manifest) |',
     '| description     | Text          | nullable        | 简短描述（在清单中使用） |'),
    ('| content         | Text          | NOT NULL        | Full skill instructions (Markdown) |',
     '| content         | Text          | NOT NULL        | 完整 Skill 说明 (Markdown) |'),
    ('Things to know about the skill table:', '关于 skill 表的注意事项：'),
    ('- Access control is managed through the `access_grant` table (resource_type `skill`)', '- 访问控制通过 `access_grant` 表（resource_type 为 `skill`）管理'),
    ('- `description` is injected into the system prompt as part of the manifest; `content` is loaded on-demand via the `view_skill` builtin tool', '- `description` 作为清单的一部分被注入系统提示词；`content` 是通过 `view_skill` 内置工具按需加载的'),
    ('## Tag Table', '## Tag 表'),
    ('## Tool Table', '## Tool 表'),
    ('| specs           | JSON          | -               | Tool specifications   |',
     '| specs           | JSON          | -               | 工具规范   |'),
    ('| valves          | JSON          | -               | Tool control settings |',
     '| valves          | JSON          | -               | 工具控制设置 |'),
    ('## User Table', '## User 表'),
    ('| username          | String(50)    | nullable         | User\'s unique username     |',
     '| username          | String(50)    | nullable         | 用户的唯一用户名     |'),
    ('| profile_image_url | Text          | -                | Profile image path         |',
     '| profile_image_url | Text          | -                | 头像路径         |'),
    ('| bio               | Text          | nullable         | User\'s biography           |',
     '| bio               | Text          | nullable         | 用户简介           |'),
    ('| gender            | Text          | nullable         | User\'s gender              |',
     '| gender            | Text          | nullable         | 用户性别              |'),
    ('| date_of_birth     | Date          | nullable         | User\'s date of birth       |',
     '| date_of_birth     | Date          | nullable         | 用户出生日期       |'),
    ('| last_active_at    | BigInteger    | -                | Last activity timestamp    |',
     '| last_active_at    | BigInteger    | -                | 最近活动时间戳    |'),
    ('| api_key           | String        | UNIQUE, nullable | API authentication key     |',
     '| api_key           | String        | UNIQUE, nullable | API 认证密钥     |'),
    ('| settings          | JSON          | nullable         | User preferences           |',
     '| settings          | JSON          | nullable         | 用户首选项           |'),
    ('| info              | JSON          | nullable         | Additional user info       |',
     '| info              | JSON          | nullable         | 额外的用户信息       |'),
    ('| oauth_sub         | Text          | UNIQUE           | OAuth subject identifier   |',
     '| oauth_sub         | Text          | UNIQUE           | OAuth 主题标识符   |'),
    ('| scim              | JSON          | nullable         | SCIM provisioning data     |',
     '| scim              | JSON          | nullable         | SCIM 配置数据     |'),
    ('Things to know about the user table:', '关于 user 表的注意事项：'),
    ('- One-to-One relationship with `oauth_session` table (via `user_id` foreign key)', '- 与 `oauth_session` 表一对一关系（通过 `user_id` 外键）'),
    ('The `scim` field\'s expected structure:', '`scim` 字段的预期结构：'),
    ('# externalId from the identity provider', '# 来自身份提供商的 externalId'),
    ('# Multiple providers can be stored simultaneously', '# 可以同时存储多个提供商'),
    ('**Why this column was added:**', '**为何添加此列：**'),
    ('- **SCIM account linking**: Stores per-provider `externalId` values from SCIM provisioning, enabling identity providers (like Azure AD, Okta) to match users by their external identifiers rather than relying solely on email.', '- **SCIM 账户关联**：存储来自 SCIM 配置的每个提供商的 `externalId` 值，使身份提供商（如 Azure AD、Okta）能够通过其外部标识符匹配用户，而不是仅仅依赖电子邮件。'),
    ('- **Multi-provider support**: The per-provider key structure allows a single user to be provisioned from multiple identity providers simultaneously, each storing their own `externalId`.', '- **多提供商支持**：按提供商的密钥结构允许单个用户同时由多个身份提供商配置，每个提供商存储其自己的 `externalId`。'),
    ('- **OAuth fallback**: When looking up a user by `externalId`, the system falls back to matching against `oauth_sub` if no `scim` entry is found, enabling seamless linking of SCIM-provisioned and OAuth-authenticated accounts.', '- **OAuth 后备**：通过 `externalId` 查找用户时，如果未找到 `scim` 条目，系统将回退到与 `oauth_sub` 匹配，从而实现 SCIM 配置账户与 OAuth 认证账户的无缝链接。'),
    ('## Entity Relationship Diagram', '## 实体关系图 (ERD)'),
    ('To help visualize the relationship between the tables, refer to the below Entity Relationship Diagram (ERD) generated with Mermaid.', '为帮助可视化表之间的关系，请参考下面使用 Mermaid 生成的实体关系图（ERD）。'),
    ('## Database Encryption with SQLCipher', '## 使用 SQLCipher 加密数据库'),
    ('For enhanced security, Open WebUI supports at-rest encryption for its primary SQLite database using SQLCipher. This is recommended for deployments handling sensitive data where using a larger database like PostgreSQL is not needed.',
     '为了增强安全性，Open WebUI 支持使用 SQLCipher 对其主 SQLite 数据库进行静态加密。对于处理敏感数据且不需要使用更大数据库（如 PostgreSQL）的部署，建议使用此功能。'),
    ('### Prerequisites', '### 前置条件'),
    ('SQLCipher encryption requires additional dependencies that are **not included by default**. Before using this feature, you must install:',
     'SQLCipher 加密需要一些**默认未包含**的额外依赖项。在使用此功能之前，你必须安装：'),
    ('- The **SQLCipher system library** (e.g., `libsqlcipher-dev` on Debian/Ubuntu, `sqlcipher` on macOS via Homebrew)',
     '- **SQLCipher 系统库**（例如，在 Debian/Ubuntu 上是 `libsqlcipher-dev`，在 macOS 上通过 Homebrew 是 `sqlcipher`）'),
    ('- The **`sqlcipher3-wheels`** Python package (`pip install sqlcipher3-wheels`)',
     '- **`sqlcipher3-wheels`** Python 包 (`pip install sqlcipher3-wheels`)'),
    ('For Docker users, this means building a custom image with these dependencies included.',
     '对于 Docker 用户，这意味着需要构建一个包含这些依赖项的自定义镜像。'),
    ('### Configuration', '### 配置'),
    ('To enable encryption, set the following environment variables:',
     '要启用加密，请设置以下环境变量：'),
    ('# Required: Set the database type to use SQLCipher', '# 必需：设置数据库类型为使用 SQLCipher'),
    ('# Required: Set a secure password for database encryption', '# 必需：设置数据库加密的安全密码'),
    ('When these are set and a full `DATABASE_URL` is **not** explicitly defined, Open WebUI will automatically create and use an encrypted database file at `./data/webui.db`.',
     '当设置了这些变量并且**没有**显式定义完整的 `DATABASE_URL` 时，Open WebUI 将自动在 `./data/webui.db` 处创建并使用加密的数据库文件。'),
    ('### Important Notes', '### 重要说明'),
    ('- The **`DATABASE_PASSWORD`** environment variable is **required** when using `sqlite+sqlcipher`.', '- 使用 `sqlite+sqlcipher` 时，**必须**设置 **`DATABASE_PASSWORD`** 环境变量。'),
    ('- The **`DATABASE_TYPE`** variable tells Open WebUI which connection logic to use. Setting it to `sqlite+sqlcipher` activates the encryption feature.', '- **`DATABASE_TYPE`** 变量告诉 Open WebUI 使用哪种连接逻辑。将其设置为 `sqlite+sqlcipher` 会激活加密功能。'),
    ('- **Keep the password secure**, as it is needed to decrypt and access all application data.', '- **确保密码安全**，因为解密和访问所有应用数据都需要它。'),
    ('- **Losing the password means losing access to all data** in the encrypted database.', '- **丢失密码意味着无法访问加密数据库中的所有数据**。'),
    (':::warning Migrating Existing Data to SQLCipher', ':::warning 将现有数据迁移到 SQLCipher'),
    ('**Open WebUI does not support automatic migration from an unencrypted SQLite database to an encrypted SQLCipher database.** If you enable SQLCipher on an existing installation, the application will fail to read your existing unencrypted data.',
     '**Open WebUI 不支持从非加密 SQLite 数据库自动迁移到加密的 SQLCipher 数据库。** 如果你在现有安装上启用 SQLCipher，应用程序将无法读取你现有的非加密数据。'),
    ('To use SQLCipher with existing data, you must either:', '要将 SQLCipher 与现有数据一起使用，你必须选择以下方法之一：'),
    ('1. **Start fresh** - Enable SQLCipher on a new installation and have users export/re-import their chats manually',
     '1. **重新开始** - 在新安装上启用 SQLCipher，并让用户手动导出/重新导入他们的聊天'),
    ('2. **Manual database migration** - Use external SQLite/SQLCipher tools to export data from the unencrypted database and import it into a new encrypted database (advanced users only)',
     '2. **手动数据库迁移** - 使用外部 SQLite/SQLCipher 工具从非加密数据库导出数据，并将其导入新的加密数据库中（仅限高级用户）'),
    ('3. **Use filesystem-level encryption** - Consider alternatives like LUKS (Linux) or BitLocker (Windows) for at-rest encryption without database-level changes',
     '3. **使用文件系统级加密** - 考虑使用 LUKS (Linux) 或 BitLocker (Windows) 等替代方案进行静态加密，而无需更改数据库级别'),
    ('4. **Switch to PostgreSQL** - For multi-user deployments, PostgreSQL with TLS provides encryption in transit and can be combined with encrypted storage',
     '4. **切换到 PostgreSQL** - 对于多用户部署，具有 TLS 的 PostgreSQL 提供了传输中的加密，并且可以与加密存储结合使用'),
    ('### Related Database Environment Variables', '### 相关的数据库环境变量'),
    ('| `DATABASE_TYPE` | `None` | Set to `sqlite+sqlcipher` for encrypted SQLite |', '| `DATABASE_TYPE` | `None` | 对于加密的 SQLite，设置为 `sqlite+sqlcipher` |'),
    ('| `DATABASE_PASSWORD` | - | Encryption password (required for SQLCipher) |', '| `DATABASE_PASSWORD` | - | 加密密码（SQLCipher 必需） |'),
    ('| `DATABASE_ENABLE_SQLITE_WAL` | `False` | Enable Write-Ahead Logging for better performance |', '| `DATABASE_ENABLE_SQLITE_WAL` | `False` | 启用预写式日志 (WAL) 以获得更好的性能 |'),
    ('| `DATABASE_SQLITE_PRAGMA_SYNCHRONOUS` | `NORMAL` | SQLite sync mode (safe with WAL, avoids fsync per txn) |', '| `DATABASE_SQLITE_PRAGMA_SYNCHRONOUS` | `NORMAL` | SQLite 同步模式（与 WAL 结合安全，避免每个事务执行 fsync） |'),
    ('| `DATABASE_SQLITE_PRAGMA_BUSY_TIMEOUT` | `5000` | Write-lock wait time in milliseconds |', '| `DATABASE_SQLITE_PRAGMA_BUSY_TIMEOUT` | `5000` | 写锁等待时间（毫秒） |'),
    ('| `DATABASE_SQLITE_PRAGMA_CACHE_SIZE` | `-65536` | Page cache size (negative = KiB; ≈ 64 MB) |', '| `DATABASE_SQLITE_PRAGMA_CACHE_SIZE` | `-65536` | 页面缓存大小（负数 = KiB; ≈ 64 MB） |'),
    ('| `DATABASE_SQLITE_PRAGMA_TEMP_STORE` | `MEMORY` | Temp table storage (`MEMORY` keeps temps in RAM) |', '| `DATABASE_SQLITE_PRAGMA_TEMP_STORE` | `MEMORY` | 临时表存储（`MEMORY` 将临时表保存在 RAM 中） |'),
    ('| `DATABASE_SQLITE_PRAGMA_MMAP_SIZE` | `268435456` | Memory-mapped I/O size in bytes (≈ 256 MB) |', '| `DATABASE_SQLITE_PRAGMA_MMAP_SIZE` | `268435456` | 内存映射 I/O 大小（以字节为单位，≈ 256 MB） |'),
    ('| `DATABASE_SQLITE_PRAGMA_JOURNAL_SIZE_LIMIT` | `67108864` | Max WAL file size after checkpoint (≈ 64 MB) |', '| `DATABASE_SQLITE_PRAGMA_JOURNAL_SIZE_LIMIT` | `67108864` | 检查点后最大 WAL 文件大小（≈ 64 MB） |'),
    ('| `DATABASE_POOL_SIZE` | `None` | Database connection pool size |', '| `DATABASE_POOL_SIZE` | `None` | 数据库连接池大小 |'),
    ('| `DATABASE_POOL_TIMEOUT` | `30` | Pool connection timeout in seconds |', '| `DATABASE_POOL_TIMEOUT` | `30` | 连接池超时时间（秒） |'),
    ('| `DATABASE_POOL_RECYCLE` | `3600` | Pool connection recycle time in seconds |', '| `DATABASE_POOL_RECYCLE` | `3600` | 连接池回收时间（秒） |'),
    ('For more details, see the [Environment Variable Configuration](/reference/env-configuration) documentation.', '更多详情，请参阅 [环境变量配置](/reference/env-configuration) 文档。')
]

for old, new in replacements:
    content = content.replace(old, new)

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print("done db4")
