import os
import pathlib

# Docker.md
filepath = 'd:/Github/open-webui-docs/docs/features/open-terminal/terminals/tab-deployment/Docker.md'
with open(filepath, 'r', encoding='utf-8') as f: content = f.read()
replacements = [
    ('## Prerequisites', '## 前置条件'),
    ('- [Docker Engine](https://docs.docker.com/engine/install/) installed and running', '- 已安装并运行 [Docker Engine](https://docs.docker.com/engine/install/)'),
    ('- Open WebUI running (or ready to deploy alongside)', '- Open WebUI 正在运行（或准备好一同部署）'),
    ('- [Open WebUI Enterprise License](https://openwebui.com/enterprise) (required for production use)', '- [Open WebUI 企业版许可证](https://openwebui.com/enterprise)（生产环境使用必须）'),
    ('## Quick start with Docker Compose', '## 使用 Docker Compose 快速开始'),
    ('This Compose file deploys Open WebUI and the Terminals orchestrator together.', '此 Compose 文件将 Open WebUI 和 Terminals 编排器一起部署。'),
    ('Set the shared API key in a `.env` file next to your Compose file:', '在 Compose 文件旁边的 `.env` 文件中设置共享 API 密钥：'),
    ('Then start everything:', '然后启动所有内容：'),
    ('Open WebUI will be available at `http://localhost:3000`. When any user activates a terminal, the orchestrator provisions their personal container automatically.', 'Open WebUI 将在 `http://localhost:3000` 上可用。当任何用户激活终端时，编排器会自动配置其个人容器。'),
    (':::warning Docker socket access', ':::warning Docker 套接字访问'),
    ('The orchestrator needs access to the Docker socket (`/var/run/docker.sock`) to manage containers. For production, use a Docker socket proxy like [Tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) to restrict the API calls it can make.', '编排器需要访问 Docker 套接字 (`/var/run/docker.sock`) 来管理容器。在生产环境中，请使用 Docker 套接字代理，如 [Tecnativa/docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy)，以限制其可以进行的 API 调用。'),
    ('<summary>Configuration reference</summary>', '<summary>配置参考</summary>'),
    ('| Variable | Default | Description |', '| 变量 | 默认值 | 描述 |'),
    ('| `TERMINALS_BACKEND` | `docker` | Backend type. Set to `docker` for this deployment mode. |', '| `TERMINALS_BACKEND` | `docker` | 后端类型。在此部署模式下设置为 `docker`。 |'),
    ('| `TERMINALS_API_KEY` | (empty) | Shared secret for authenticating requests from Open WebUI. Required. |', '| `TERMINALS_API_KEY` | (空) | 用于认证来自 Open WebUI 请求的共享密钥。必须提供。 |'),
    ('| `TERMINALS_IMAGE` | `ghcr.io/open-webui/open-terminal:latest` | Default container image for user terminals. |', '| `TERMINALS_IMAGE` | `ghcr.io/open-webui/open-terminal:latest` | 用户终端的默认容器镜像。 |'),
    ('| `TERMINALS_PORT` | `3000` | Port the orchestrator listens on. |', '| `TERMINALS_PORT` | `3000` | 编排器监听的端口。 |'),
    ('| `TERMINALS_HOST` | `0.0.0.0` | Address the orchestrator binds to. |', '| `TERMINALS_HOST` | `0.0.0.0` | 编排器绑定的地址。 |'),
    ('| `TERMINALS_NETWORK` | (empty) | Docker network for user containers. When set, containers communicate by name. |', '| `TERMINALS_NETWORK` | (空) | 用户容器的 Docker 网络。设置后，容器通过名称进行通信。 |'),
    ('| `TERMINALS_DOCKER_HOST` | `127.0.0.1` | Address for published container ports. Only relevant without `TERMINALS_NETWORK`. |', '| `TERMINALS_DOCKER_HOST` | `127.0.0.1` | 发布容器端口的地址。仅在没有 `TERMINALS_NETWORK` 时相关。 |'),
    ('| `TERMINALS_DATA_DIR` | `data/terminals` | Host directory for per-user workspace data. |', '| `TERMINALS_DATA_DIR` | `data/terminals` | 存储每个用户工作区数据的宿主机目录。 |'),
    ('| `TERMINALS_IDLE_TIMEOUT_MINUTES` | `0` (disabled) | Minutes of inactivity before a container is stopped. Set to `30` for typical usage. |', '| `TERMINALS_IDLE_TIMEOUT_MINUTES` | `0` (禁用) | 容器停止前的非活动分钟数。对于典型使用，请设置为 `30`。 |'),
    ('| `TERMINALS_MAX_CPU` | (empty) | CPU limit for user containers (e.g., `2`). |', '| `TERMINALS_MAX_CPU` | (空) | 用户容器的 CPU 限制（例如 `2`）。 |'),
    ('| `TERMINALS_MAX_MEMORY` | (empty) | Memory limit for user containers (e.g., `4Gi`). |', '| `TERMINALS_MAX_MEMORY` | (空) | 用户容器的内存限制（例如 `4Gi`）。 |'),
    ('| `TERMINALS_OPEN_WEBUI_URL` | (empty) | If set, validates incoming JWTs against this Open WebUI instance instead of using `TERMINALS_API_KEY`. |', '| `TERMINALS_OPEN_WEBUI_URL` | (空) | 如果设置，则针对此 Open WebUI 实例验证传入的 JWT，而不是使用 `TERMINALS_API_KEY`。 |'),
    ('<summary>Container lifecycle details</summary>', '<summary>容器生命周期详情</summary>'),
    ('**Naming.** Containers are named `terminals-{policy_id}-{user_id}`, making them easy to filter with `docker ps --filter "label=managed-by=terminals"`.', '**命名。** 容器命名为 `terminals-{policy_id}-{user_id}`，从而便于使用 `docker ps --filter "label=managed-by=terminals"` 进行过滤。'),
    ('**Health checks.** After creating a container, the orchestrator polls its `/health` endpoint until it returns HTTP 200 (up to 15 seconds). Only then does it start proxying traffic.', '**健康检查。** 创建容器后，编排器会轮询其 `/health` 端点，直到返回 HTTP 200（最多 15 秒）。只有这样它才开始代理流量。'),
    ('**Reconciliation.** If the orchestrator restarts, it rediscovers existing running containers by their labels and recovers their API keys from the container configuration. This prevents duplicate containers from being created.', '**协调（Reconciliation）。** 如果编排器重新启动，它会通过标签重新发现现有的正在运行的容器，并从容器配置中恢复它们的 API 密钥。这可以防止创建重复的容器。'),
    ('**Conflict handling.** If a container with the same name already exists (e.g., from a previous failed cleanup), the orchestrator force-removes the old container and retries up to 3 times.', '**冲突处理。** 如果同名的容器已经存在（例如，来自之前失败的清理），编排器会强制删除旧容器并最多重试 3 次。'),
    ('## Limitations', '## 限制'),
    ('- **Single host.** All user containers run on one Docker host. For high availability or larger teams, use the Kubernetes Operator backend.', '- **单主机。** 所有用户容器都在一个 Docker 主机上运行。如需高可用性或服务更大的团队，请使用 Kubernetes Operator 后端。'),
    ('- **No built-in HA.** If the orchestrator goes down, active terminal sessions are interrupted (though containers keep running and are reconciled on restart).', '- **没有内置高可用性。** 如果编排器宕机，活动的终端会话将被中断（尽管容器继续运行并在重新启动时被协调）。'),
    ('- **Docker socket required.** The orchestrator needs access to the Docker socket to manage containers.', '- **需要 Docker 套接字。** 编排器需要访问 Docker 套接字来管理容器。')
]
for old, new in replacements: content = content.replace(old, new)
with open(filepath, 'w', encoding='utf-8') as f: f.write(content)

# Kubernetes.md
filepath = 'd:/Github/open-webui-docs/docs/features/open-terminal/terminals/tab-deployment/Kubernetes.md'
with open(filepath, 'r', encoding='utf-8') as f: content = f.read()
replacements = [
    ('## Prerequisites', '## 前置条件'),
    ('- A running Kubernetes cluster (v1.24+)', '- 一个正在运行的 Kubernetes 集群 (v1.24+)'),
    ('- [Helm](https://helm.sh/docs/intro/install/) v3 installed', '- 已安装 [Helm](https://helm.sh/docs/intro/install/) v3'),
    ('- `kubectl` configured to access your cluster', '- 已配置 `kubectl` 以访问你的集群'),
    ('- [Open WebUI Enterprise License](https://openwebui.com/enterprise) (required for production use)', '- [Open WebUI 企业版许可证](https://openwebui.com/enterprise)（生产环境使用必须）'),
    ('## Deploy with Helm', '## 使用 Helm 部署'),
    ('The Open WebUI Helm chart includes Terminals as an optional subchart. Add a `terminals` section to your values file:', 'Open WebUI Helm chart 包含 Terminals 作为可选子 chart。在你的 values 文件中添加 `terminals` 部分：'),
    ('Then install or upgrade:', '然后安装或升级：'),
    (':::tip Auto-configured connection', ':::tip 自动配置连接'),
    ('When `terminals.enabled` is `true`, the chart automatically sets `TERMINAL_SERVER_CONNECTIONS` to point at the in-cluster orchestrator. No manual connection setup is needed.', '当 `terminals.enabled` 为 `true` 时，chart 会自动设置 `TERMINAL_SERVER_CONNECTIONS` 指向集群内的编排器。不需要手动配置连接。'),
    ('### Verify', '### 验证'),
    ('# Check that all pods are running', '# 检查所有 pod 是否正在运行'),
    ('# Check that the CRD is installed', '# 检查 CRD 是否已安装'),
    ('## What gets deployed', '## 部署了什么'),
    ('When `terminals.enabled: true`, the chart creates:', '当 `terminals.enabled: true` 时，chart 将创建：'),
    ('| Resource | Purpose |', '| 资源 | 目的 |'),
    ('| **CRD** (`terminals.openwebui.com`) | Defines the `Terminal` custom resource |', '| **CRD** (`terminals.openwebui.com`) | 定义 `Terminal` 自定义资源 |'),
    ('| **Operator Deployment** | Kopf controller that watches Terminal CRs and provisions Pods, Services, PVCs, Secrets |', '| **Operator Deployment** | Kopf 控制器，监听 Terminal CR 并配置 Pod、Service、PVC、Secret |'),
    ('| **Orchestrator Deployment + Service** | FastAPI service that receives requests from Open WebUI and proxies to user Pods |', '| **Orchestrator Deployment + Service** | FastAPI 服务，接收来自 Open WebUI 的请求并代理到用户 Pod |'),
    ('| **Secret** | Shared API key (auto-generated if not provided) |', '| **Secret** | 共享 API 密钥（如果未提供则自动生成） |'),
    ('For **each user terminal**, the operator creates a Pod, Service, Secret (API key), and optionally a PVC for persistent storage.', '对于**每个用户终端**，Operator 会创建一个 Pod、Service、Secret（API 密钥），以及可选的用于持久化存储的 PVC。'),
    ('## Lifecycle', '## 生命周期'),
    ('When a user activates a terminal, the orchestrator creates a `Terminal` CR. The operator provisions a Pod with a Service, Secret, and optional PVC. Once the Pod passes readiness checks, the orchestrator proxies traffic to it.', '当用户激活终端时，编排器会创建一个 `Terminal` CR。Operator 会配置一个带有 Service、Secret 和可选 PVC 的 Pod。一旦 Pod 通过就绪检查，编排器就会将流量代理到它。'),
    ('When a terminal has been idle longer than `idleTimeoutMinutes`, the operator deletes the Pod but keeps the PVC and Secret. On the next request, a fresh Pod is created with the same PVC reattached, so **user data persists** across idle cycles.', '当终端空闲时间超过 `idleTimeoutMinutes` 时，Operator 会删除 Pod，但保留 PVC 和 Secret。在下一次请求时，将创建一个连接了相同 PVC 的新 Pod，因此在空闲周期内**用户数据能够持久化**。'),
    ('# List all terminals', '# 列出所有终端'),
    ('# Inspect a specific terminal', '# 检查特定的终端'),
    ('# Delete a terminal (child resources are garbage-collected automatically)', '# 删除终端（子资源会自动被垃圾回收）'),
    ('## Monitoring', '## 监控'),
    ('# Operator logs', '# Operator 日志'),
    ('# Orchestrator logs', '# 编排器日志'),
    ('<summary>Terminal CRD reference</summary>', '<summary>Terminal CRD 参考</summary>'),
    ('### Spec fields', '### Spec 字段'),
    ('| Field | Type | Default | Description |', '| 字段 | 类型 | 默认值 | 描述 |'),
    ('| `userId` | string | *(required)* | Open WebUI user ID |', '| `userId` | 字符串 | *(必填)* | Open WebUI 用户 ID |'),
    ('| `image` | string | `ghcr.io/open-webui/open-terminal:latest` | Container image |', '| `image` | 字符串 | `ghcr.io/open-webui/open-terminal:latest` | 容器镜像 |'),
    ('| `resources.requests.cpu` | string | `100m` | CPU request |', '| `resources.requests.cpu` | 字符串 | `100m` | CPU 请求 |'),
    ('| `resources.requests.memory` | string | `256Mi` | Memory request |', '| `resources.requests.memory` | 字符串 | `256Mi` | 内存请求 |'),
    ('| `resources.limits.cpu` | string | `1` | CPU limit |', '| `resources.limits.cpu` | 字符串 | `1` | CPU 限制 |'),
    ('| `resources.limits.memory` | string | `1Gi` | Memory limit |', '| `resources.limits.memory` | 字符串 | `1Gi` | 内存限制 |'),
    ('| `idleTimeoutMinutes` | integer | `30` | Idle timeout before Pod is stopped |', '| `idleTimeoutMinutes` | 整数 | `30` | Pod 停止前的空闲超时 |'),
    ('| `packages` | array | `[]` | Apt packages to pre-install |', '| `packages` | 数组 | `[]` | 预安装的 Apt 包 |'),
    ('| `pipPackages` | array | `[]` | Pip packages to pre-install |', '| `pipPackages` | 数组 | `[]` | 预安装的 Pip 包 |'),
    ('| `persistence.enabled` | boolean | `true` | Enable persistent storage |', '| `persistence.enabled` | 布尔值 | `true` | 启用持久化存储 |'),
    ('| `persistence.size` | string | `1Gi` | PVC size |', '| `persistence.size` | 字符串 | `1Gi` | PVC 大小 |'),
    ('| `persistence.storageClass` | string | *(cluster default)* | Storage class |', '| `persistence.storageClass` | 字符串 | *(集群默认)* | Storage class (存储类) |'),
    ('### Status fields', '### Status 字段'),
    ('| Field | Description |', '| 字段 | 描述 |'),
    ('| `phase` | `Pending`, `Provisioning`, `Running`, `Idle`, or `Error` |', '| `phase` | `Pending`, `Provisioning`, `Running`, `Idle`, 或 `Error` |'),
    ('| `podName` | Name of the terminal Pod |', '| `podName` | 终端 Pod 的名称 |'),
    ('| `serviceUrl` | In-cluster URL for the terminal |', '| `serviceUrl` | 终端的集群内 URL |'),
    ('| `apiKeySecret` | Secret holding the terminal\'s API key |', '| `apiKeySecret` | 保存终端 API 密钥的 Secret |'),
    ('| `lastActivityAt` | Timestamp of last proxied request |', '| `lastActivityAt` | 上次代理请求的时间戳 |'),
    ('<summary>Full Helm values reference</summary>', '<summary>完整 Helm values 参考</summary>'),
    ('| Key | Default | Description |', '| 键 | 默认值 | 描述 |'),
    ('| `terminals.enabled` | `false` | Enable the Terminals subchart |', '| `terminals.enabled` | `false` | 启用 Terminals 子 chart |'),
    ('| `terminals.apiKey` | (empty) | Shared API key (auto-generated if empty) |', '| `terminals.apiKey` | (空) | 共享 API 密钥（如果为空则自动生成） |'),
    ('| `terminals.existingSecret` | (empty) | Pre-existing Secret name (key: `api-key`) |', '| `terminals.existingSecret` | (空) | 预存在的 Secret 名称 (键: `api-key`) |'),
    ('| `terminals.crd.install` | `true` | Install the Terminal CRD |', '| `terminals.crd.install` | `true` | 安装 Terminal CRD |'),
    ('| `terminals.operator.image.repository` | `ghcr.io/open-webui/terminals-operator` | Operator image |', '| `terminals.operator.image.repository` | `ghcr.io/open-webui/terminals-operator` | Operator 镜像 |'),
    ('| `terminals.operator.image.tag` | `latest` | Operator image tag |', '| `terminals.operator.image.tag` | `latest` | Operator 镜像标签 |'),
    ('| `terminals.operator.replicaCount` | `1` | Operator replicas |', '| `terminals.operator.replicaCount` | `1` | Operator 副本数 |'),
    ('| `terminals.orchestrator.image.repository` | `ghcr.io/open-webui/terminals` | Orchestrator image |', '| `terminals.orchestrator.image.repository` | `ghcr.io/open-webui/terminals` | 编排器镜像 |'),
    ('| `terminals.orchestrator.image.tag` | `latest` | Orchestrator image tag |', '| `terminals.orchestrator.image.tag` | `latest` | 编排器镜像标签 |'),
    ('| `terminals.orchestrator.backend` | `kubernetes-operator` | Backend type |', '| `terminals.orchestrator.backend` | `kubernetes-operator` | 后端类型 |'),
    ('| `terminals.orchestrator.terminalImage` | `ghcr.io/open-webui/open-terminal:latest` | Default image for user Pods |', '| `terminals.orchestrator.terminalImage` | `ghcr.io/open-webui/open-terminal:latest` | 用户 Pod 的默认镜像 |'),
    ('| `terminals.orchestrator.idleTimeoutMinutes` | `30` | Idle timeout (minutes) |', '| `terminals.orchestrator.idleTimeoutMinutes` | `30` | 空闲超时（分钟） |'),
    ('| `terminals.orchestrator.service.type` | `ClusterIP` | Orchestrator Service type |', '| `terminals.orchestrator.service.type` | `ClusterIP` | 编排器 Service 类型 |'),
    ('| `terminals.orchestrator.service.port` | `8080` | Orchestrator Service port |', '| `terminals.orchestrator.service.port` | `8080` | 编排器 Service 端口 |'),
    ('<summary>RBAC requirements (manual install only)</summary>', '<summary>RBAC 要求（仅限手动安装）</summary>'),
    ('If not using the Helm chart, the operator\'s ServiceAccount needs a ClusterRole with:', '如果不使用 Helm chart，Operator 的 ServiceAccount 需要一个具有以下权限的 ClusterRole：'),
    ('| Resource | Verbs |', '| 资源 | 动作 (Verbs) |')
]
for old, new in replacements: content = content.replace(old, new)
with open(filepath, 'w', encoding='utf-8') as f: f.write(content)
print("done terminals")
