import pathlib
#!/usr/bin/env python3
"""Translate plugin/tools/index.mdx and plugin/functions/index.mdx"""

def translate(filepath, pairs):
    content = open(filepath, encoding='utf-8').read()
    changed = False
    not_found = []
    for old, new in pairs:
        if old in content:
            content = content.replace(old, new, 1)
            changed = True
        else:
            not_found.append(old[:60])
    if changed:
        import os
        with open(filepath, 'w', encoding='utf-8', newline='') as f:
            f.write(content)
        print(f'TRANSLATED: {os.path.basename(filepath)}')
    else:
        print(f'UNCHANGED: {os.path.basename(filepath)}')
    for s in not_found:
        print(f'  NOT FOUND: {s}')

BASE = pathlib.Path(__file__).resolve().parents[1] / "docs"

# ============================================================
# plugin/tools/index.mdx
# ============================================================
translate(f'{BASE}/features/extensibility/plugin/tools/index.mdx', [
    ('title: "Tools"', 'title: "Tools"'),  # keep
    ('# What are Tools?', '# 什么是 Tools？'),
    (':::danger \u26a0\ufe0f Critical Security Warning\n**Workspace Tools and Functions execute arbitrary Python code on your server.** Only install from trusted sources, review code before importing, and restrict Workspace access to trusted administrators only. Granting a user the ability to create or import Tools is equivalent to giving them shell access to the server. For full details, see the [Plugin Security Warning](/features/extensibility/plugin/).\n:::',
     ':::danger ⚠️ 重要安全警告\n**Workspace Tools 和 Functions 在你的服务器上执行任意 Python 代码。** 只从受信任的来源安装，导入前审查代码，并将 Workspace 访问限制为受信任的管理员。授予用户创建或导入 Tools 的能力等同于给予他们服务器的 shell 访问权限。详情参见[插件安全警告](/features/extensibility/plugin/)。\n:::'),
    ('\u2699\ufe0f Tools are the various ways you can extend an LLM\u2019s capabilities beyond simple text generation. When enabled, they allow your chatbot to do amazing things \u2014 like search the web, scrape data, generate images, talk back using AI voices, and more.\n\nBecause there are several ways to integrate \u201cTools\u201d in Open WebUI, it\'s important to understand which type you are using.',
     '⚙️ Tools 是你扩展 LLM 能力、超越简单文本生成的各种方式。启用后，它们允许你的聊天机器人做惊人的事情——比如搜索网络、抓取数据、生成图像、使用 AI 语音回应等。\n\n由于在 Open WebUI 中有几种集成"Tools"的方式，了解你使用的是哪种类型非常重要。'),
    ('## Tooling Taxonomy: Which "Tool" are you using?\n\n\U0001f9e9 Users often encounter the term "Tools" in different contexts. Here is how to distinguish them:',
     '## 工具分类：你使用的是哪种"Tool"？\n\n🧩 用户经常在不同上下文中遇到"Tools"这个术语。以下是区分它们的方法：'),
    ('### 1. Native Features (Built-in)\nThese are deeply integrated into Open WebUI and generally don\'t require external scripts.\n- **Web Search**: Integrated via engines like SearXNG, Google, or Tavily.\n- **URL Fetching**: Extract text content directly from websites using `#` or native tools.\n- **Image Generation**: Integrated with DALL-E, ComfyUI, or Automatic1111.\n- **Memory**: The ability for models to remember facts about you across chats.\n- **RAG (Knowledge)**: The ability to query uploaded documents (`#`).\n\nIn [**Native Mode**](#built-in-system-tools-nativeagentic-mode), these features are exposed as **Tools** that the model can call independently.',
     '### 1. 原生功能（内置）\n这些深度集成在 Open WebUI 中，通常不需要外部脚本。\n- **网络搜索**：通过 SearXNG、Google 或 Tavily 等引擎集成。\n- **URL 获取**：使用 `#` 或原生工具直接从网站提取文本内容。\n- **图像生成**：与 DALL-E、ComfyUI 或 Automatic1111 集成。\n- **记忆**：模型在对话之间记住关于你的事实的能力。\n- **RAG（知识）**：查询上传文档的能力（`#`）。\n\n在[**原生模式**](#built-in-system-tools-nativeagentic-mode)下，这些功能作为模型可独立调用的 **Tools** 暴露。'),
    ('### 2. Workspace Tools (Custom Plugins)\nThese are **Python scripts** that run directly within the Open WebUI environment.\n- **Capability**: Can do anything Python can do (web scraping, complex math, API calls).\n- **Access**: Managed via the `Workspace` menu. \n- **Safety**: Always review code before importing, as these run on your server.\n- **\u26a0\ufe0f Security Warning**: Normal or untrusted users should **not** be given permission to access the Workspace Tools section. This access allows a user to upload and execute arbitrary Python code on your server, which could lead to a full system compromise.',
     '### 2. Workspace Tools（自定义插件）\n这些是直接在 Open WebUI 环境中运行的 **Python 脚本**。\n- **能力**：可以做 Python 能做的任何事情（网络抓取、复杂数学、API 调用）。\n- **访问**：通过 `Workspace` 菜单管理。\n- **安全**：始终在导入前审查代码，因为这些在你的服务器上运行。\n- **⚠️ 安全警告**：普通或不受信任的用户**不应**被授予访问 Workspace Tools 部分的权限。此访问允许用户在你的服务器上上传和执行任意 Python 代码，可能导致全系统被入侵。'),
    ('### 3. MCP (Model Context Protocol)\n\n\U0001f50c MCP is an open standard that allows LLMs to interact with external data and tools.\n- **Native HTTP MCP**: Open WebUI can connect directly to any MCP server that exposes an HTTP/SSE endpoint.\n- **MCPO (Proxy)**: Most community MCP servers use `stdio` (local command line). To use these in Open WebUI, you use the [**MCPO Proxy**](../../plugin/tools/openapi-servers/mcp.mdx) to bridge the connection.',
     '### 3. MCP（模型上下文协议）\n\n🔌 MCP 是一个允许 LLM 与外部数据和工具交互的开放标准。\n- **原生 HTTP MCP**：Open WebUI 可以直接连接到任何暴露 HTTP/SSE 端点的 MCP 服务器。\n- **MCPO（代理）**：大多数社区 MCP 服务器使用 `stdio`（本地命令行）。要在 Open WebUI 中使用这些，你可以使用 [**MCPO 代理**](../../plugin/tools/openapi-servers/mcp.mdx)来桥接连接。'),
    ('### 4. OpenAPI / Function Calling Servers\nGeneric web servers that provide an OpenAPI (`.json` or `.yaml`) specification. Open WebUI can ingest these specs and treat every endpoint as a tool.',
     '### 4. OpenAPI / 函数调用服务器\n提供 OpenAPI（`.json` 或 `.yaml`）规范的通用 Web 服务器。Open WebUI 可以摄取这些规范并将每个端点视为工具。'),
    ('## How to Install & Manage Workspace Tools\n\n\U0001f4e6 Workspace Tools are the most common way to extend your instance with community features.\n\n1. Go to [Community Tool Library](https://openwebui.com/search)\n2. Choose a Tool, then click the **Get** button.\n3. Enter your Open WebUI instance\'s URL (e.g. `http://localhost:3000`).\n4. Click **Import to WebUI**.\n\n:::warning Safety Tip\nNever import a Tool you don\'t recognize or trust. These are Python scripts and might run unsafe code on your host system. **Crucially, ensure you only grant "Tool" permissions to trusted users**, as the ability to create or import tools is equivalent to the ability to run arbitrary code on the server.\n:::',
     '## 如何安装和管理 Workspace Tools\n\n📦 Workspace Tools 是用社区功能扩展实例最常见的方式。\n\n1. 前往[社区工具库](https://openwebui.com/search)\n2. 选择一个 Tool，然后点击 **Get** 按钮。\n3. 输入你的 Open WebUI 实例 URL（如 `http://localhost:3000`）。\n4. 点击 **Import to WebUI**。\n\n:::warning 安全提示\n切勿导入你不认识或不信任的 Tool。这些是 Python 脚本，可能在你的主机系统上运行不安全代码。**至关重要的是，只向受信任的用户授予"Tool"权限**，因为创建或导入工具的能力等同于在服务器上运行任意代码的能力。\n:::'),
    ('## How to Use Tools in Chat\n\n\U0001f527 Once installed or connected, here\'s how to enable them for your conversations:\n\n### Option 1: Enable on-the-fly (Specific Chat)\nWhile chatting, click the **\u2795 (plus)** icon in the input area. You\'ll see a list of available Tools \u2014 you can enable them specifically for that session.\n\n### Option 2: Enable by Default (Global/Model Level)\n1. Go to **Workspace \u27a1\ufe0f Models**.\n2. Choose the model you\'re using and click the \u270f\ufe0f edit icon.\n3. Scroll to the **Tools** section.\n4. \u2705 Check the Tools you want this model to always have access to by default.\n5. Click **Save**.\n\nFor models that support it, **Native tool calling mode** (see [Tool Calling Modes](#tool-calling-modes-default-vs-native) below) lets the model itself decide which of the attached tools to call on each turn. This replaces the older prompt-injection "auto-tool" filter approach and is the recommended way to let the model auto-select tools.',
     '## 如何在对话中使用 Tools\n\n🔧 安装或连接后，以下是为对话启用它们的方法：\n\n### 选项 1：即时启用（特定对话）\n聊天时，点击输入区域中的 **➕（加号）** 图标。你将看到可用 Tools 列表——你可以专门为该会话启用它们。\n\n### 选项 2：默认启用（全局/模型级别）\n1. 前往 **Workspace ➡️ 模型**。\n2. 选择你使用的模型并点击 ✏️ 编辑图标。\n3. 滚动到 **Tools** 部分。\n4. ✅ 勾选你希望此模型默认始终访问的 Tools。\n5. 点击**保存**。\n\n对于支持的模型，**原生工具调用模式**（见下方[工具调用模式](#tool-calling-modes-default-vs-native)）让模型自己决定每轮调用哪些附加工具。这取代了旧的基于提示注入的"auto-tool"过滤方法，是让模型自动选择工具的推荐方式。'),
    (':::caution Attached Tools Still Require User Access\nAttaching a workspace tool to a model does **not** bypass access control. When a user chats with the model, Open WebUI checks whether **that specific user** has read access to each attached tool. Tools the user cannot access are silently skipped \u2014 the model won\'t be able to call them.\n\n**Example scenario**: An admin creates a private tool and attaches it to a model shared with all users. Regular users chatting with this model will **not** have the tool available because they don\'t have read access to the tool itself.\n\n**Solution**: Make sure users who need the model\'s tools also have read access to each tool (via access grants, group permissions, or by making the tool public). The "Workspace \u2192 Tools" permission controls whether users can *create and manage* tools \u2014 it does **not** affect whether model-attached tools work for them.\n:::',
     ':::caution 附加的 Tools 仍然需要用户访问权限\n将 Workspace Tool 附加到模型**不会**绕过访问控制。当用户与模型聊天时，Open WebUI 会检查**该特定用户**是否有每个附加工具的读取权限。用户无法访问的工具会被静默跳过——模型将无法调用它们。\n\n**示例场景**：管理员创建一个私有工具并将其附加到与所有用户共享的模型。与此模型聊天的普通用户将**无法使用**该工具，因为他们没有工具本身的读取权限。\n\n**解决方案**：确保需要模型工具的用户也对每个工具有读取权限（通过访问授权、组权限或将工具设为公开）。"Workspace → Tools"权限控制用户是否可以*创建和管理*工具——它**不影响**模型附加的工具是否对他们有效。\n:::'),
    ('## Tool Calling Modes: Default vs. Native', '## 工具调用模式：Default 模式与 Native 模式'),
    (':::danger Default Mode Is Legacy and No Longer Supported \u2014 Use Native Mode\n**All models should be configured for Native (Agentic) Mode.** Default Mode is a legacy prompt-injection fallback that predates widespread native function-calling support in LLMs. It is **no longer supported**: it will not receive feature work, bug fixes, or built-in system tools, and it is incompatible with modern Open WebUI features (Agentic Research, Interleaved Thinking, built-in Memory/Notes/Knowledge/Channels tools, web-search/image-gen/code-interpreter tool injection).\n\nDefault Mode still exists in the dropdown only so that instances with older tool code paths keep running while admins migrate. If your deployment is still on Default Mode, switch every model to Native Mode (see [How to Enable Native Mode](#how-to-enable-native-mode-agentic-mode) below). If a specific model has trouble with Native Mode, the correct fix is to pick a better model for tool calling \u2014 not to fall back to Default.\n:::',
     ':::danger Default 模式已过时且不再受支持——请使用 Native 模式\n**所有模型都应配置为 Native（Agentic）模式。** Default 模式是一种遗留的提示注入回退，早于 LLM 中普遍的原生函数调用支持。它**不再受支持**：不会收到功能工作、错误修复或内置系统工具，并且与现代 Open WebUI 功能不兼容（Agentic Research、交错思考、内置 Memory/Notes/Knowledge/Channels 工具、网络搜索/图像生成/代码解释器工具注入）。\n\nDefault 模式仍然存在于下拉菜单中，只是为了让具有旧工具代码路径的实例在管理员迁移时继续运行。如果你的部署仍在 Default 模式下，将每个模型切换到 Native 模式（见下方[如何启用 Native 模式](#how-to-enable-native-mode-agentic-mode)）。如果特定模型在 Native 模式下有问题，正确的解决方法是选择更好的工具调用模型——而不是回退到 Default。\n:::'),
    ('Open WebUI exposes two modes in **Model Settings \u2192 Advanced Params \u2192 Function Calling**: **Native Mode (Agentic Mode)** \u2014 the only supported mode \u2014 and **Default Mode**, kept in the UI for backwards compatibility only.',
     'Open WebUI 在**模型设置 → 高级参数 → 函数调用**中提供两种模式：**Native 模式（Agentic 模式）**——唯一受支持的模式——以及 **Default 模式**，仅为向后兼容性保留在 UI 中。'),
    ('### \U0001f534 Default Mode (Prompt-based) \u2014 Legacy / Unsupported\n\n:::warning Unsupported\nDefault Mode is **legacy and no longer supported**. It is documented here for reference only. New deployments must use Native Mode; existing deployments should migrate. Bug reports, feature requests, and support questions about Default Mode behavior will not be actioned.\n:::',
     '### 🔴 Default 模式（基于提示）— 遗留/不受支持\n\n:::warning 不受支持\nDefault 模式**已过时且不再受支持**。此处仅供参考。新部署必须使用 Native 模式；现有部署应迁移。关于 Default 模式行为的错误报告、功能请求和支持问题将不会被处理。\n:::'),
    ('In Default Mode, Open WebUI manages tool selection by injecting a long prompt template that guides the model to output a tool request in a bespoke format. It was a reasonable approach in 2023; it has been obsolete since mainstream providers and open-weights models gained proper function-calling APIs.\n\nWhy it is legacy:\n- **Breaks KV cache.** The injected prompt changes every turn, preventing LLM engines from reusing cached key-value pairs. Every message pays the full prefill cost again.\n- **Higher latency and token cost.** Bulky tool-description prompts on every turn.\n- **Unreliable for multi-step chaining.** Parsing natural-language tool requests is fragile compared to structured tool calls.\n- **Cannot access built-in system tools.** Memory, Notes, Knowledge, Channels, Agentic Research, Interleaved Thinking, and the tool-injected Web Search / Image Generation / Code Interpreter features are **Native-only**.\n- **Does not support modern capabilities.** Every new feature shipped since 2024 targets Native Mode.',
     '在 Default 模式下，Open WebUI 通过注入一个长提示模板来管理工具选择，引导模型以定制格式输出工具请求。这在 2023 年是合理的方法；自主流提供商和开放权重模型获得适当的函数调用 API 以来，它已经过时了。\n\n为什么它已过时：\n- **破坏 KV 缓存。** 注入的提示每轮都会改变，阻止 LLM 引擎重用缓存的键值对。每条消息都要再次支付完整的预填充成本。\n- **更高的延迟和令牌成本。** 每轮都有大量工具描述提示。\n- **对多步骤链接不可靠。** 解析自然语言工具请求比结构化工具调用更脆弱。\n- **无法访问内置系统工具。** 记忆、笔记、知识、频道、Agentic Research、交错思考以及工具注入的网络搜索/图像生成/代码解释器功能都是**仅 Native 模式**可用的。\n- **不支持现代能力。** 2024 年以来发布的每个新功能都针对 Native 模式。'),
    ('### \U0001f7e2 Native Mode (Agentic Mode / System Function Calling) \u2014 The Only Supported Mode\nNative Mode (also called **Agentic Mode**) leverages the model\'s built-in capability to handle tool definitions and return structured tool calls (JSON). This is the **recommended mode** for all models that support it \u2014 which includes the vast majority of modern models (2024+).\n\n:::warning Model Quality Matters\n**Agentic tool calling requires high-quality models to work reliably.** While small local models may technically support function calling, they often struggle with the complex reasoning required for multi-step tool usage. For best results, use frontier models like **GPT-5**, **Claude 4.5 Sonnet**, **Gemini 3 Flash**, or **MiniMax M2.5**. Small local models may produce malformed JSON or fail to follow the strict state management required for agentic behavior.\n:::',
     '### 🟢 Native 模式（Agentic 模式/系统函数调用）— 唯一受支持的模式\nNative 模式（也称为 **Agentic 模式**）利用模型内置的能力处理工具定义并返回结构化工具调用（JSON）。这是所有支持它的模型的**推荐模式**——包括绝大多数现代模型（2024+）。\n\n:::warning 模型质量很重要\n**Agentic 工具调用需要高质量模型才能可靠工作。** 虽然小型本地模型在技术上可能支持函数调用，但它们通常难以完成多步骤工具使用所需的复杂推理。为获得最佳结果，使用前沿模型如 **GPT-5**、**Claude 4.5 Sonnet**、**Gemini 3 Flash** 或 **MiniMax M2.5**。小型本地模型可能产生格式错误的 JSON 或无法遵循 Agentic 行为所需的严格状态管理。\n:::'),
    ('#### Why use Native Mode (Agentic Mode)?\n- **Speed & Efficiency**: Lower latency as it avoids bulky prompt-based tool selection.\n- **KV Cache Friendly**: Tool definitions are sent as structured parameters (not injected into the prompt), so they don\'t invalidate the KV cache between turns. This can significantly reduce latency and token costs.\n- **Reliability**: Higher accuracy in following tool schemas (with quality models).\n- **Multi-step Chaining**: Essential for **Agentic Research** and **Interleaved Thinking** where a model needs to call multiple tools in succession.\n- **Autonomous Decision-Making**: Models can decide when to search, which tools to use, and how to combine results.\n- **System Tools**: Only Native Mode unlocks the [built-in system tools](#built-in-system-tools-nativeagentic-mode) (memory, notes, knowledge, channels, etc.).',
     '#### 为什么使用 Native 模式（Agentic 模式）？\n- **速度与效率**：避免大量基于提示的工具选择，延迟更低。\n- **KV 缓存友好**：工具定义作为结构化参数发送（而不是注入提示中），因此不会使轮次间的 KV 缓存失效。这可以显著降低延迟和令牌成本。\n- **可靠性**：遵循工具模式的准确性更高（使用质量模型）。\n- **多步骤链接**：对于需要连续调用多个工具的 **Agentic Research** 和**交错思考**至关重要。\n- **自主决策**：模型可以决定何时搜索、使用哪些工具以及如何组合结果。\n- **系统工具**：只有 Native 模式才能解锁[内置系统工具](#built-in-system-tools-nativeagentic-mode)（记忆、笔记、知识、频道等）。'),
    ('#### How to Enable Native Mode (Agentic Mode)\nNative Mode can be enabled at two levels:\n\n1.  **Universal Default for Every Model (Fastest \u2014 Recommended)**:\n    *   Navigate to **Admin Panel \u2192 Settings \u2192 Models**.\n    *   Click the **Settings** button at the **top right** of the models list \u2014 this opens **global model parameters**, which apply to *every* model in your instance (current and future) unless a specific model overrides them.\n    *   Under **Model Parameters**, set **Function Calling** to `Native`.\n    *   Save. All existing models that haven\'t explicitly set their own value, and all models you add later, inherit `Native`. You do **not** need to edit them one by one.\n2.  **Per-Model Override**:\n    *   In **Admin Panel \u2192 Settings \u2192 Models**, pick a specific model and click its edit button.\n    *   Under **Model Parameters**, set **Function Calling** to `Native`. This value overrides the global default for that model only.\n    *   Use this when a specific model needs different parameters \u2014 otherwise prefer the global setting.\n3.  **Per-Chat Override**:\n    *   Inside a chat, open **Chat Controls** (right sidebar).\n    *   Under **Advanced Params**, set **Function Calling** to `Native`. Applies to that chat only.',
     '#### 如何启用 Native 模式（Agentic 模式）\nNative 模式可以在两个级别启用：\n\n1.  **所有模型的通用默认值（最快——推荐）**：\n    *   导航到**管理面板 → 设置 → 模型**。\n    *   点击模型列表**右上角**的**设置**按钮——这将打开**全局模型参数**，适用于你实例中的*每个*模型（当前和未来），除非特定模型覆盖它们。\n    *   在**模型参数**下，将**函数调用**设置为 `Native`。\n    *   保存。所有尚未明确设置自己值的现有模型以及你之后添加的所有模型都继承 `Native`。你**不需要**逐一编辑它们。\n2.  **按模型覆盖**：\n    *   在**管理面板 → 设置 → 模型**中，选择特定模型并点击其编辑按钮。\n    *   在**模型参数**下，将**函数调用**设置为 `Native`。此值仅覆盖该模型的全局默认值。\n    *   当特定模型需要不同参数时使用此选项——否则优先使用全局设置。\n3.  **按对话覆盖**：\n    *   在对话中，打开**对话控制**（右侧边栏）。\n    *   在**高级参数**下，将**函数调用**设置为 `Native`。仅适用于该对话。'),
    (':::tip Set Function Calling Globally \u2014 Once, For All Models\nTired of switching every model to Native one at a time? The **global model parameters** panel (the **Settings** button at the top right of **Admin Panel \u2192 Settings \u2192 Models**) lets you configure any model parameter \u2014 `function_calling`, temperature, top_p, max_tokens, etc. \u2014 **once, for every model in your Open WebUI instance**. Values set there become the default for every existing model that hasn\'t overridden them *and* every model you add later. Set `Function Calling = Native` there, save, done.\n:::',
     ':::tip 全局设置函数调用——一次性，适用于所有模型\n厌倦了逐个将每个模型切换到 Native？**全局模型参数**面板（**管理面板 → 设置 → 模型**右上角的**设置**按钮）让你配置任何模型参数——`function_calling`、temperature、top_p、max_tokens 等——**一次性，适用于 Open WebUI 实例中的每个模型**。在那里设置的值成为每个尚未覆盖它们的现有模型*和*你之后添加的每个模型的默认值。在那里设置 `Function Calling = Native`，保存，完成。\n:::'),
    ('### Built-in System Tools (Native/Agentic Mode)\n\n\U0001f6e0\ufe0f When **Native Mode (Agentic Mode)** is enabled, Open WebUI automatically injects powerful system tools. This unlocks truly agentic behaviors where capable models (like GPT-5, Claude 4.5 Sonnet, Gemini 3 Flash, or MiniMax M2.5) can perform multi-step research, explore knowledge bases, or manage user memory autonomously.',
     '### 内置系统工具（Native/Agentic 模式）\n\n🛠️ 当启用 **Native 模式（Agentic 模式）** 时，Open WebUI 自动注入强大的系统工具。这解锁了真正的 Agentic 行为，使有能力的模型（如 GPT-5、Claude 4.5 Sonnet、Gemini 3 Flash 或 MiniMax M2.5）能够自主执行多步骤研究、探索知识库或管理用户记忆。'),
    (':::info Automatic Timezone Detection\nOpen WebUI automatically detects and stores your timezone when you log in. This allows time-related tools and features to provide accurate local times without any manual configuration. Your timezone is determined from your browser settings.\n:::',
     ':::info 自动时区检测\nOpen WebUI 在你登录时自动检测并存储你的时区。这允许与时间相关的工具和功能提供准确的本地时间，无需任何手动配置。你的时区由浏览器设置确定。\n:::'),
    (':::warning Knowledge Tool Injection Depends on Attachments\nKnowledge tool availability changes based on whether the model has attached knowledge. Use the **Knowledge Tool Availability** matrix above as the source of truth.\n\n- With attachments: the model gets scoped knowledge tools.\n- Without attachments: the model gets KB discovery tools.\n- `list_knowledge` and `list_knowledge_bases` are mutually exclusive.\n:::',
     ':::warning 知识工具注入取决于附件\n知识工具的可用性根据模型是否有附加知识而变化。使用上面的**知识工具可用性**矩阵作为参考依据。\n\n- 有附件时：模型获得范围限定的知识工具。\n- 无附件时：模型获得 KB 发现工具。\n- `list_knowledge` 和 `list_knowledge_bases` 是互斥的。\n:::'),
    (':::caution Attached Knowledge Still Requires User Access\nAttaching a knowledge base to a custom model does **not** bypass access control. When a user chats with the model, `query_knowledge_files` checks whether **that specific user** has permission to access each attached knowledge item. Items the user cannot access are silently excluded from search results.\n\n**Access requirements by knowledge type:**',
     ':::caution 附加的知识仍然需要用户访问权限\n将知识库附加到自定义模型**不会**绕过访问控制。当用户与模型聊天时，`query_knowledge_files` 会检查**该特定用户**是否有权访问每个附加的知识项目。用户无法访问的项目会被静默排除在搜索结果之外。\n\n**按知识类型的访问要求：**'),
    (':::info Recommended KB Tool Workflow\n**With attached knowledge:**\n1. First call `list_knowledge` to discover attached KBs, files, and notes\n2. Use `query_knowledge_files` to search file contents (auto-scoped to attachments)\n3. Use `view_file` or `view_knowledge_file` to read specific files \u2014 use `offset` and `max_chars` for large files\n\n**Without attached knowledge:**\n1. First call `list_knowledge_bases` to discover what knowledge is available\n2. Then use `query_knowledge_files` to search file contents within relevant KBs\n3. If still empty, the files may not be embedded yet, or you may have **Full Context mode enabled** which bypasses the vector store\n\n**Do NOT use Full Context mode with knowledge tools** \u2014 Full Context injects file content directly and doesn\'t store embeddings, so `query_knowledge_files` will return empty. Use Focused Retrieval (default) for tool-based access.\n:::',
     ':::info 推荐的 KB 工具工作流\n**有附加知识时：**\n1. 首先调用 `list_knowledge` 发现附加的 KB、文件和笔记\n2. 使用 `query_knowledge_files` 搜索文件内容（自动范围限定为附件）\n3. 使用 `view_file` 或 `view_knowledge_file` 读取特定文件——对大文件使用 `offset` 和 `max_chars`\n\n**无附加知识时：**\n1. 首先调用 `list_knowledge_bases` 发现可用的知识\n2. 然后使用 `query_knowledge_files` 在相关 KB 中搜索文件内容\n3. 如果仍然为空，文件可能尚未嵌入，或者你可能启用了**全文上下文模式**，该模式绕过向量存储\n\n**不要将全文上下文模式与知识工具一起使用**——全文上下文直接注入文件内容而不存储嵌入，因此 `query_knowledge_files` 将返回空。使用聚焦检索（默认）进行基于工具的访问。\n:::'),
    (':::tip Knowledge Base Tools and Hybrid Search\nThe native `query_knowledge_files` tool uses **hybrid search + reranking** when `ENABLE_RAG_HYBRID_SEARCH` is enabled in admin settings, giving you the same search quality as the standard RAG pipeline. When hybrid search is disabled, it falls back to simple vector search.\n:::',
     ':::tip 知识库工具和混合搜索\n当在管理设置中启用 `ENABLE_RAG_HYBRID_SEARCH` 时，原生 `query_knowledge_files` 工具使用**混合搜索 + 重排序**，为你提供与标准 RAG 管道相同的搜索质量。当混合搜索禁用时，它回退到简单的向量搜索。\n:::'),
    ('Quick rule: `list_knowledge` and `list_knowledge_bases` are mutually exclusive.',
     '快速规则：`list_knowledge` 和 `list_knowledge_bases` 是互斥的。'),
])

# ============================================================
# plugin/functions/index.mdx
# ============================================================
translate(f'{BASE}/features/extensibility/plugin/functions/index.mdx', [
    ('title: "Functions"', 'title: "Functions"'),  # keep
    ('# \U0001f9e9 Functions\n\n:::danger \u26a0\ufe0f Critical Security Warning\n**Functions execute arbitrary Python code on your server.** Function creation is restricted to administrators only. Only install from trusted sources and review code before importing. A malicious Function could access your file system, exfiltrate data, or compromise your entire system. For full details, see the [Plugin Security Warning](/features/extensibility/plugin/).\n:::',
     '# 🧩 Functions\n\n:::danger ⚠️ 重要安全警告\n**Functions 在你的服务器上执行任意 Python 代码。** Function 创建仅限管理员。只从受信任的来源安装，导入前审查代码。恶意 Function 可能访问你的文件系统、泄露数据或危害整个系统。详情参见[插件安全警告](/features/extensibility/plugin/)。\n:::'),
    ('Functions are **modular Python plugins** that extend the capabilities of Open WebUI itself. While [Tools](/features/extensibility/plugin/tools/) give LLMs the ability to call external APIs during inference, Functions change how the platform behaves at a deeper level. They can add entirely new "models" powered by any Python logic, intercept and transform every message flowing through the system, or place interactive buttons directly in the chat UI.\n\nThe possibilities are broad: connect a proprietary AI provider, build a smart home controller that responds to natural language, create a database query interface, add real-time translation to every conversation, enforce compliance policies, generate charts from data, or trigger external workflows with a button click. If you can write it in Python, you can turn it into a Function.\n\nFunctions are stored in the database as Python source code, dynamically loaded at runtime, and executed server-side. Administrators create and manage them; regular users interact with the results.',
     'Functions 是**模块化 Python 插件**，扩展 Open WebUI 本身的能力。[Tools](/features/extensibility/plugin/tools/) 让 LLM 在推理时调用外部 API，而 Functions 在更深层次上改变平台的行为方式。它们可以添加由任何 Python 逻辑驱动的全新"模型"、拦截和转换流经系统的每条消息，或者直接在对话 UI 中放置交互式按钮。\n\n可能性非常广泛：连接专有 AI 提供商、构建响应自然语言的智能家居控制器、创建数据库查询界面、为每次对话添加实时翻译、执行合规策略、从数据生成图表，或通过按钮点击触发外部工作流。如果你能用 Python 编写它，你就能将其变成 Function。\n\nFunctions 以 Python 源代码的形式存储在数据库中，在运行时动态加载，并在服务器端执行。管理员创建和管理它们；普通用户与结果交互。'),
    ('## Function Types\n\nOpen WebUI supports three types of Functions. The type is **auto-detected** from the class name in your Python code, so you never need to configure it manually.',
     '## Function 类型\n\nOpen WebUI 支持三种类型的 Functions。类型根据你 Python 代码中的类名**自动检测**，因此你无需手动配置。'),
    ('### Pipe Functions\n\nA Pipe registers itself as a new "model" in Open WebUI. When a user selects it and sends a message, the `pipe()` method handles the entire request with no LLM backend required. This makes Pipes incredibly versatile:\n\n- **Model providers**: Integrate APIs that don\'t follow the OpenAI protocol (Anthropic native, Google Vertex, custom inference servers).\n- **Agents & workflows**: Build multi-step agents that call tools, search the web, and reason across multiple turns.\n- **Non-LLM interfaces**: Create a smart home controller, a database query tool, a search engine, a calculator, or a code executor. Anything that takes user input and returns a response.\n- **Proxies & routers**: Route requests through your own logic, add caching, load balancing, or cost tracking.\n\nA single Pipe can also expose **multiple models** (called a "manifold") by defining a `pipes()` method that returns a list of model identifiers.\n\n\u2192 **[Pipe Function Guide](./pipe)**',
     '### Pipe Functions\n\nPipe 将自己注册为 Open WebUI 中的新"模型"。当用户选择它并发送消息时，`pipe()` 方法处理整个请求，无需 LLM 后端。这使 Pipes 极其灵活：\n\n- **模型提供商**：集成不遵循 OpenAI 协议的 API（Anthropic 原生、Google Vertex、自定义推理服务器）。\n- **代理和工作流**：构建调用工具、搜索网络并跨多轮推理的多步骤代理。\n- **非 LLM 界面**：创建智能家居控制器、数据库查询工具、搜索引擎、计算器或代码执行器。任何接受用户输入并返回响应的东西。\n- **代理和路由器**：通过你自己的逻辑路由请求，添加缓存、负载均衡或成本追踪。\n\n单个 Pipe 还可以通过定义返回模型标识符列表的 `pipes()` 方法暴露**多个模型**（称为"manifold"）。\n\n→ **[Pipe Function 指南](./pipe)**'),
    ('### Filter Functions\n\nA Filter sits between the user and the model, intercepting data at three stages:\n\n- **`inlet()`**: Modifies the request **before** it reaches the model (add context, sanitize input, detect language, enforce rate limits, estimate token costs).\n- **`stream()`**: Intercepts **streamed chunks** from the model in real time (censor content, replace terms, track token usage).\n- **`outlet()`**: Processes the completed response **after** it\'s generated (log to observability platforms, format citations, append disclaimers, cache responses).\n\nFilters enable powerful cross-cutting concerns like real-time translation, content moderation, prompt injection detection, A/B testing, compliance logging, and PII redaction, all without modifying the underlying model.\n\nFilters can be applied globally (to all models) or attached to specific models. Toggleable filters let users enable/disable them per-chat.\n\n\u2192 **[Filter Function Guide](./filter)**',
     '### Filter Functions\n\nFilter 位于用户和模型之间，在三个阶段拦截数据：\n\n- **`inlet()`**：在请求到达模型**之前**修改它（添加上下文、净化输入、检测语言、执行速率限制、估算令牌成本）。\n- **`stream()`**：实时拦截来自模型的**流式块**（审查内容、替换术语、追踪令牌使用）。\n- **`outlet()`**：在生成**之后**处理完整响应（记录到可观测性平台、格式化引用、追加免责声明、缓存响应）。\n\nFilters 支持强大的横切关注点，如实时翻译、内容审核、提示注入检测、A/B 测试、合规日志记录和 PII 删除，所有这些都不需要修改底层模型。\n\nFilters 可以全局应用（到所有模型）或附加到特定模型。可切换的过滤器让用户按对话启用/禁用它们。\n\n→ **[Filter Function 指南](./filter)**'),
    ('### Action Functions\n\nAn Action adds a custom button to the chat message toolbar. When a user clicks it, the `action()` method runs with full access to the event system for real-time UI feedback, user prompts, and confirmations.\n\nActions can do anything Python can do: summarize or translate a message, copy formatted output, pin important messages, export conversations to external systems, trigger a CI/CD pipeline, send a Slack notification, generate a PDF report, run a code snippet, or kick off an external workflow.\n\n\u2192 **[Action Function Guide](./action)**',
     '### Action Functions\n\nAction 向对话消息工具栏添加自定义按钮。当用户点击它时，`action()` 方法运行，可完全访问事件系统以进行实时 UI 反馈、用户提示和确认。\n\nActions 可以做 Python 能做的任何事情：摘要或翻译消息、复制格式化输出、固定重要消息、将对话导出到外部系统、触发 CI/CD 管道、发送 Slack 通知、生成 PDF 报告、运行代码片段或启动外部工作流。\n\n→ **[Action Function 指南](./action)**'),
    ('## How Functions Work\n\n### Type Detection\n\nWhen you save a Function, Open WebUI scans the Python source code for a top-level class named `Pipe`, `Filter`, or `Action`. The first match determines the function type. You never need to manually set the type because it\'s inferred from the code.',
     '## Functions 的工作原理\n\n### 类型检测\n\n保存 Function 时，Open WebUI 扫描 Python 源代码中名为 `Pipe`、`Filter` 或 `Action` 的顶级类。第一个匹配项确定函数类型。你永远不需要手动设置类型，因为它是从代码推断出来的。'),
    ('### Module Loading & Caching\n\nThe Python source code is loaded via `exec()` into a temporary module namespace. Once loaded, the module is cached in memory (`request.app.state.FUNCTIONS`) and only reloaded when the source code changes. Import statements in your code are automatically rewritten to resolve within the Open WebUI package namespace.',
     '### 模块加载和缓存\n\nPython 源代码通过 `exec()` 加载到临时模块命名空间中。一旦加载，模块就会缓存在内存中（`request.app.state.FUNCTIONS`），只有在源代码更改时才重新加载。你代码中的 import 语句会自动重写以在 Open WebUI 包命名空间内解析。'),
    ('### Frontmatter\n\nA triple-quoted docstring at the top of the file is parsed as YAML frontmatter for metadata:',
     '### 前置信息\n\n文件顶部的三引号文档字符串被解析为元数据的 YAML 前置信息：'),
    (':::tip Automatic Dependency Installation\nWhen `requirements` is specified in the frontmatter, Open WebUI automatically installs the listed packages via `pip` the first time the function loads. This is controlled by the `PIP_INSTALL_FRONTMATTER_REQUIREMENTS` environment variable (enabled by default).\n:::',
     ':::tip 自动依赖安装\n当在前置信息中指定 `requirements` 时，Open WebUI 在函数第一次加载时通过 `pip` 自动安装列出的包。这由 `PIP_INSTALL_FRONTMATTER_REQUIREMENTS` 环境变量控制（默认启用）。\n:::'),
    ('## Installing Functions\n\n### From the Community Library\n\n1. Browse the [Community Function Library](https://openwebui.com/search).\n2. Click **Get** on the function you want.\n3. Enter your Open WebUI instance URL (e.g., `http://localhost:3000`).\n4. Click **Import to Open WebUI**. You\'ll be redirected to the Function Editor.\n5. Review the code, then click **Save**.\n\n:::warning\nAlways review the source code before importing. Community functions are user-contributed and **run directly on your server**.\n:::\n\n### From a URL\n\n1. Go to **Admin Panel \u2192 Functions**.\n2. Click **Import from URL** and paste a link to the Python file.\n   - GitHub URLs are automatically converted to raw file URLs.\n3. Review and save.\n\n### Create Manually\n\n1. Go to **Admin Panel \u2192 Functions**.\n2. Click **Create**.\n3. Enter an ID (alphanumeric and underscores only), name, and description.\n4. Write your Python code in the editor.\n5. Click **Save**. The function type is auto-detected from your code.',
     '## 安装 Functions\n\n### 从社区库\n\n1. 浏览[社区 Function 库](https://openwebui.com/search)。\n2. 点击你想要的 Function 上的 **Get**。\n3. 输入你的 Open WebUI 实例 URL（如 `http://localhost:3000`）。\n4. 点击 **Import to Open WebUI**。你将被重定向到 Function 编辑器。\n5. 审查代码，然后点击**保存**。\n\n:::warning\n导入前务必审查源代码。社区 Functions 是用户贡献的，**直接在你的服务器上运行**。\n:::\n\n### 从 URL\n\n1. 前往**管理面板 → Functions**。\n2. 点击**从 URL 导入**，粘贴 Python 文件的链接。\n   - GitHub URL 会自动转换为原始文件 URL。\n3. 审查并保存。\n\n### 手动创建\n\n1. 前往**管理面板 → Functions**。\n2. 点击**创建**。\n3. 输入 ID（仅限字母数字和下划线）、名称和描述。\n4. 在编辑器中编写 Python 代码。\n5. 点击**保存**。函数类型从你的代码自动检测。'),
    ('## Managing Functions\n\n### Admin Controls\n\nFunctions are managed from **Admin Panel \u2192 Functions**. Each function has the following controls:',
     '## 管理 Functions\n\n### 管理员控制\n\nFunctions 从**管理面板 → Functions** 管理。每个 Function 具有以下控制：'),
    ('### Assigning Functions to Specific Models\n\nInstead of making a Filter or Action global, you can attach it to specific models:\n\n1. Go to **Workspace \u2192 Models**.\n2. Edit the target model.\n3. In the **Filters** or **Actions** section, select the functions you want to attach.\n\nThis allows different models to use different filters. For example, you might apply a content-moderation filter only on public-facing models.',
     '### 将 Functions 分配给特定模型\n\n除了将 Filter 或 Action 设为全局，你也可以将其附加到特定模型：\n\n1. 前往 **Workspace → 模型**。\n2. 编辑目标模型。\n3. 在 **Filters** 或 **Actions** 部分，选择要附加的 Functions。\n\n这允许不同模型使用不同的过滤器。例如，你可能只在面向公众的模型上应用内容审核过滤器。'),
    ('### Toggleable Filters\n\nFilters can be made user-toggleable by setting `self.toggle = True` in `__init__`. When toggleable, users see an on/off switch in the chat input area and can enable or disable the filter per-conversation. Filters without `self.toggle` are always-on when active.',
     '### 可切换的 Filters\n\n通过在 `__init__` 中设置 `self.toggle = True`，可以使 Filters 用户可切换。可切换时，用户在对话输入区域看到开/关开关，可以按对话启用或禁用过滤器。没有 `self.toggle` 的 Filters 在激活时始终开启。'),
    ('## Valves & UserValves\n\nFunctions support a two-tier configuration system built on [Pydantic](https://docs.pydantic.dev/):\n\n**Valves** are ideal for API keys, model endpoints, and global behavior settings. **UserValves** let individual users customize behavior (e.g., their preferred language, output format, or personal API key).\n\nBoth are defined as nested Pydantic `BaseModel` classes inside your `Pipe`, `Filter`, or `Action` class. The admin-configured values are stored in the database and loaded automatically at runtime.\n\n\u2192 **[Valves Development Guide](/features/extensibility/plugin/development/valves)**',
     '## Valves & UserValves\n\nFunctions 支持基于 [Pydantic](https://docs.pydantic.dev/) 的双层配置系统：\n\n**Valves** 非常适合 API 密钥、模型端点和全局行为设置。**UserValves** 让个人用户自定义行为（如他们的首选语言、输出格式或个人 API 密钥）。\n\n两者都定义为你的 `Pipe`、`Filter` 或 `Action` 类内的嵌套 Pydantic `BaseModel` 类。管理员配置的值存储在数据库中，并在运行时自动加载。\n\n→ **[Valves 开发指南](/features/extensibility/plugin/development/valves)**'),
    ('## Functions vs Tools: When to Use Which', '## Functions vs Tools：何时使用哪个'),
    ('## Development Resources', '## 开发资源'),
])

print('Done!')
